--[[ 

isAffectedby = {Master-at-Arms, Thaumaturge, Staff/Weapon Expert, Elfborn/Precise Strikes}  (only pet skills or skills that can't crit are not affected by elfborn)
list is at https://docs.google.com/spreadsheets/d/1AMVpTmhUMBz-7gPOwKNSBA2VnX-Wjju8xIpPk0wk1Io

Data Format: T/F if affected by {EXPERTORMIGHTY, MASTEROFARMS, THAUMATURGE, WEAPONEXPERT, CRITS, PENETRATION}

--]]

local AbilityData = {
	[40267] = {true, false, true, false, true, true}, --Anti-Calvary Caltrops
	[38561] = {true, false, true, false, true, true}, --Caltrops
	[61493] = {true, false, false, false, true, true}, --Inevitable Detonation
	[61502] = {true, false, false, false, true, true}, --Proximity Detonation
	[40254] = {true, false, false, false, true, true}, --Razor Caltrops
	[40252] = {true, false, true, false, true, true}, --Razor Caltrops dot
	[38724] = {true, true, false, false, true, true}, --Acid Spray
	[38703] = {true, false, true, false, true, true}, --Acid Spray (Dot)
	[38696] = {true, false, true, false, true, true}, --Arrow Barrage
	[38722] = {true, true, false, false, true, true}, --Arrow Spray
	[85462] = {true, true, false, false, true, true}, --Ballista
	[38723] = {true, true, false, false, true, true}, --Bombard
	[38669] = {true, true, false, false, true, true}, --Draining Shot
	[38690] = {true, false, true, false, true, true}, --Endless Hail
	[38687] = {true, true, false, false, true, true}, --Focused Aim
	[17173] = {true, true, false, true, true, true}, --Heavy Attack (Bow)
	[17174] = {true, true, false, true, true, true}, --Heavy Attack (Medium, Bow)
	[38685] = {true, true, false, false, true, true}, --Lethal Arrow
	[16688] = {true, true, false, true, true, true}, --Light Attack (Bow)
	[38672] = {true, true, false, false, true, true}, --Magnum Shot
	[28869] = {true, true, false, false, true, true}, --Poison Arrow
	[44540] = {true, false, true, false, true, true}, --Poison Arrow (Dot)
	[38660] = {true, true, false, false, true, true}, --Poison Injection
	[44549] = {true, false, true, false, true, true}, --Poison Injection (Dot)
	[21929] = {true, false, true, false, true, true}, --Poisoned
	[86563] = {true, false, true, false, true, true}, --Rapid Fire
	[28879] = {true, true, false, false, true, true}, --Scatter Shot
	[28882] = {true, true, false, false, true, true}, --Snipe
	[85260] = {true, false, true, false, true, true}, --Toxic Barrage
	[85261] = {true, false, true, false, true, true}, --Toxic Barrage (Dot)
	[38645] = {true, true, false, false, true, true}, --Venom Arrow
	[44545] = {true, false, true, false, true, true}, --Venom Arrow (Dot)
	[28877] = {true, false, true, false, true, true}, --Volley
	[62912] = {true, false, true, false, true, true}, --Blockade of Fire
	[62951] = {true, false, true, false, true, true}, --Blockade of Frost
	[62990] = {true, false, true, false, true, true}, --Blockade of Storms
	[18084] = {true, false, true, false, true, true}, --Burning
	[21481] = {true, false, true, false, true, true}, --Chill
	[21487] = {true, false, true, false, true, true}, --Concussion
	[46348] = {true, true, false, false, true, true}, --Crushing Shock (Fire)
	[46350] = {true, true, false, false, true, true}, --Crushing Shock (Frost)
	[46351] = {true, true, false, false, true, true}, --Crushing Shock (Shock)
	[83683] = {true, false, true, false, true, true}, --Eye of Flame
	[83685] = {true, false, true, false, true, true}, --Eye of Frost
	[83687] = {true, false, true, false, true, true}, --Eye of Lightning
	[85127] = {true, false, true, false, true, true}, --Fiery Rage
	[62668] = {true, false, true, false, true, true}, --Fire Clench
	[39149] = {true, true, false, false, true, true}, --Fire Ring
	[38985] = {true, true, false, false, true, true}, --Flame Clench
	[39162] = {true, true, false, false, true, true}, --Flame Pulsar
	[38944] = {true, true, false, false, true, true}, --Flame Reach
	[62682] = {true, false, true, false, true, true}, --Flame Reach dot
	[29073] = {true, true, false, false, true, true}, --Flame Touch
	[62648] = {true, false, true, false, true, true}, --Flame Touch dot
	[46356] = {true, true, false, false, true, true}, --Force Pulse (Fire)
	[46357] = {true, true, false, false, true, true}, --Force Pulse (Frost)
	[46358] = {true, true, false, false, true, true}, --Force Pulse (Shock)
	[38989] = {true, true, false, false, true, true}, --Frost Clench
	[62702] = {true, false, true, false, true, true}, --Frost Clench dot
	[39163] = {true, true, false, false, true, true}, --Frost Pulsar
	[38970] = {true, true, false, false, true, true}, --Frost Reach
	[62712] = {true, false, true, false, true, true}, --Frost Reach dot
	[39151] = {true, true, false, false, true, true}, --Frost Ring
	[29078] = {true, true, false, false, true, true}, --Frost Touch
	[62692] = {true, false, true, false, true, true}, --Frost Touch dot
	[15385] = {true, true, false, true, true, true}, --Heavy Attack (Fire)
	[16321] = {true, true, false, true, true, true}, --Heavy Attack (Fire), full
	[18405] = {true, true, false, true, true, true}, --Heavy Attack (Frost)
	[18406] = {true, true, false, true, true, true}, --Heavy Attack (Frost), full
	[18396] = {true, false, true, true, true, true}, --Heavy Attack (Shock)
	[85129] = {true, false, true, false, true, true}, --Icy Rage
	[16165] = {true, true, false, true, true, true}, --Light Attack (Fire)
	[16277] = {true, true, false, true, true, true}, --Light Attack (Frost)
	[18350] = {true, true, false, true, true, true}, --Light Attack (Shock)
	[38993] = {true, true, false, false, true, true}, --Shock Clench
	[62733] = {true, false, true, false, true, true}, --Shock Clench dot
	[62743] = {true, false, true, false, true, true}, --Shock Clench Explosion
	[19277] = {true, true, false, false, true, true}, --Shock Pulse
	[38978] = {true, true, false, false, true, true}, --Shock Reach
	[62745] = {true, false, true, false, true, true}, --Shock Reach dot
	[39153] = {true, true, false, false, true, true}, --Shock Ring
	[29089] = {true, true, false, false, true, true}, --Shock Touch
	[62722] = {true, false, true, false, true, true}, --Shock Touch dot
	[39167] = {true, true, false, false, true, true}, --Storm Pulsar
	[85131] = {true, false, true, false, true, true}, --Thunderous Rage
	[45505] = {true, false, true, true, true, true}, --Tri Focus (Shock)
	[39054] = {true, false, true, false, true, true}, --Unstable Wall of Fire
	[39056] = {true, true, false, false, true, true}, --Unstable Wall of Fire Explosion
	[39071] = {true, false, true, false, true, true}, --Unstable Wall of Frost
	[39072] = {true, true, false, false, true, true}, --Unstable Wall of Frost Explosion
	[39079] = {true, false, true, false, true, true}, --Unstable Wall of Storms
	[39080] = {true, true, false, false, true, true}, --Unstable Wall of Storms Explosion
	[20660] = {true, true, false, false, true, true}, --Burning Embers
	[44373] = {true, false, true, false, true, true}, --Burning Embers dot
	[20252] = {true, true, false, false, true, true}, --Burning Talons
	[31898] = {true, false, true, false, true, true}, --Burning Talons (dot)
	[20251] = {true, true, false, false, true, true}, --Choking Talons
	[17879] = {true, false, true, false, true, true}, --Corrosive Armor
	[32792] = {true, true, false, false, true, true}, --Deep Breath (1st)
	[32794] = {true, true, false, false, true, true}, --Deep Breath (2nd)
	[32785] = {true, true, false, false, true, true}, --Draw Essence (1st)
	[32787] = {true, true, false, false, true, true}, --Draw Essence (2nd)
	[20499] = {true, true, false, false, true, true}, --Empowering Chains
	[20930] = {true, true, false, false, true, true}, --Engulfing Flames
	[31104] = {true, false, true, false, true, true}, --Engulfing Flames dot
	[32714] = {true, false, true, false, true, true}, --Eruption
	[32711] = {true, false, true, false, true, true}, --Eruption (dot)
	[32716] = {true, true, false, false, true, true}, --Ferocious Leap
	[20816] = {true, true, false, false, true, true}, --Flame Lash
	[61945] = {true, true, false, false, true, true}, --Flames of Oblivion
	[54931] = {true, true, false, false, true, true}, --Fossilize
	[28969] = {true, true, false, false, true, true}, --Inferno
	[23806] = {true, true, false, false, true, true}, --Lava Whip
	[17875] = {true, false, true, false, true, true}, --Magma Shell
	[20805] = {true, true, false, false, true, true}, --Molten Whip
	[20944] = {true, true, false, false, true, true}, --Noxious Breath
	[31103] = {true, false, true, false, true, true}, --Noxious Breath (dot)
	[31820] = {true, true, false, false, true, true}, --Obsidian Shard
	[54918] = {true, true, false, false, true, true}, --Petrify
	[20824] = {true, true, false, false, true, true}, --Power Lash
	[32684] = {true, true, false, false, true, true}, --Shattering Rocks
	[32960] = {true, false, true, false, true, true}, --Shifting Standard
	[32964] = {true, false, true, false, true, true}, --Shifting Standard
	[32948] = {true, false, true, false, true, true}, --Standard of Might
	[31816] = {true, true, false, false, true, true}, --Stone Giant
	[32720] = {true, true, false, false, true, true}, --Take Flight
	[20496] = {true, true, false, false, true, true}, --Unrelenting Grip
	[20668] = {true, true, false, false, true, true}, --Venomous Claw
	[44369] = {true, false, true, false, true, true}, --Venomous Claw (dot)
	[20326] = {true, false, true, false, true, true}, --Volatile Armor
	[62522] = {true, false, true, false, true, true}, --Blade Cloak
	[38845] = {true, true, false, false, true, true}, --Blood Craze
	[38847] = {true, true, false, false, true, true}, --Blood Craze (Off Hand)
	[38848] = {true, false, true, false, true, false}, --Blood Craze Bleed
	[38846] = {true, false, true, false, true, true}, --Bloodthirst
	[62547] = {true, false, true, false, true, true}, --Deadly Cloak (Blade Cloak)
	[28607] = {true, false, true, false, true, true}, --Flurry
	[38910] = {true, true, false, false, true, true}, --Flying Blade
	[18622] = {true, true, false, true, true, true}, --Heavy Attack (Dual Wield)
	[17169] = {true, true, false, true, true, true}, --Heavy Attack (DW)
	[17170] = {true, true, false, true, true, true}, --Heavy Attack (Medium, DW)
	[21157] = {true, true, false, false, true, true}, --Hidden Blade
	[85156] = {true, false, true, false, true, true}, --Lacerate
	[16499] = {true, true, false, true, true, true}, --Light Attack (DW)
	[62529] = {true, false, true, false, true, true}, --Quick Cloak (Blade Cloak)
	[38857] = {true, false, true, false, true, true}, --Rapid Strikes
	[85192] = {true, false, true, false, true, true}, --Rend
	[38839] = {true, true, false, false, true, true}, --Rending Slashes
	[38840] = {true, true, false, false, true, true}, --Rending Slashes (Off Hand)
	[38841] = {true, false, true, false, true, false}, --Rending Slashes Bleed
	[38914] = {true, true, false, false, true, true}, --Shrouded Daggers
	[38861] = {true, true, false, false, true, true}, --Steel Tornado
	[85182] = {true, false, true, false, true, true}, --Thrive in Chaos
	[28379] = {true, true, false, false, true, true}, --Twin Slashes
	[35312] = {true, true, false, false, true, true}, --Twin Slashes (Off hand)
	[29293] = {true, false, true, false, true, false}, --Twin Slashes Bleed
	[38891] = {true, true, false, false, true, true}, --Whirling Blades
	[28591] = {true, true, false, false, true, true}, --Whirlwind
	[40158] = {true, true, false, false, true, true}, --Dawnbreaker of Smiting
	[62314] = {true, false, true, false, true, true}, --Dawnbreaker of Smiting dot
	[40161] = {true, true, false, false, true, true}, --Flawless Dawnbreaker
	[62310] = {true, false, true, false, true, true}, --Flawless Dawnbreaker dot
	[40376] = {true, false, true, false, true, true}, --Lightweight Beast Trap
	[40375] = {true, false, true, false, true, true}, --Lightweight Beast Trap dot
	[40389] = {true, false, true, false, true, true}, --Rearming Trap
	[40392] = {true, false, true, false, true, true}, --Rearming Trap 2
	[40385] = {true, false, true, false, true, true}, --Rearming Trap dot
	[40336] = {true, true, false, false, true, true}, --Silver Leash
	[40300] = {true, true, false, false, true, true}, --Silver Shards
	[46743] = {true, true, false, false, true, true}, --Absorb Magicka
	[46746] = {true, true, false, false, true, true}, --Absorb Stamina
	[107203] = {true, true, true, false, true, true}, --Arms of Relequen
	[17904] = {true, true, false, false, true, true}, --Befouled Weapon
	[17899] = {true, true, false, false, true, true}, --Charged Weapon
	[46749] = {true, true, false, false, true, true}, --Damage Health
	[93307] = {true, true, false, false, false, true}, --Defiler
	[97883] = {true, false, true, false, false, true}, --Domihaus (fire)
	[60972] = {true, false, true, false, false, true}, --Fiery Breath
	[60973] = {true, true, false, false, false, true}, --Fiery Jaws
	[17895] = {true, true, false, false, true, true}, --Fiery Weapon
	[17897] = {true, true, false, false, true, true}, --Frozen Weapon
	[84502] = {true, false, true, false, false, true}, --Grothdarr
	[80561] = {true, false, true, false, false, true}, --Iceheart
	[109086] = {true, true, true, false, true, true}, --Ideal Arms of Relequen
	[80525] = {true, false, true, false, false, true}, --Illambris (fire)
	[80526] = {true, false, true, false, false, true}, --Illambris (lightning)
	[83409] = {true, true, false, false, false, true}, --Infernal Guardian
	[60974] = {true, true, false, false, false, true}, --Jagged Claw
	[80565] = {true, false, true, false, false, true}, --Kra'gh
	[28919] = {true, true, false, false, true, true}, --Life Drain
	[107094] = {true, false, true, false, false, true}, --Mantle of Siroria
	[59498] = {true, false, true, false, false, true}, --Mephala's Web
	[59593] = {true, true, false, false, false, true}, --Nerien'eth
	[17902] = {true, true, false, false, true, true}, --Poisoned Weapon
	[40337] = {true, true, false, false, true, true}, --Prismatic Weapon
	[80606] = {true, true, false, false, false, true}, --Selene
	[80544] = {true, true, false, false, false, true}, --Sellistrix
	[80980] = {true, true, false, false, false, true}, --Shadowrend (base attack)
	[80989] = {true, true, false, false, false, true}, --Shadowrend (tail sweep)
	[80522] = {true, false, true, false, false, true}, --Stormfist (lightning)
	[80521] = {true, true, false, false, false, true}, --Stormfist (physical)
	[80865] = {true, true, false, false, false, true}, --Tremorscale
	[61273] = {true, true, false, false, false, true}, --Valkyn Skoria (splash)
	[59596] = {true, true, false, false, false, true}, --Valkyn Skoria (target hit)
	[80490] = {true, true, false, false, false, true}, --Velidreth
	[113627] = {true, true, false, false, true, true}, --Virulent Shot
	[102136] = {true, false, true, false, false, true}, --Zaan
	[40457] = {true, false, true, false, true, true}, --Degeneration
	[63457] = {true, true, false, false, true, true}, --Ice Comet
	[63454] = {true, false, true, false, true, true}, --Ice Comet dot
	[40469] = {true, true, false, false, true, true}, --Scalding Rune
	[40468] = {true, false, true, false, true, true}, --Scalding Rune dot
	[63474] = {true, true, false, false, true, true}, --Shooting Star
	[63471] = {true, false, true, false, true, true}, --Shooting Star (dot)
	[40452] = {true, false, true, false, true, true}, --Structured Entropy
	[40473] = {true, true, false, false, true, true}, --Volcanic Rune
	[25485] = {true, true, false, false, true, true}, --Ambush
	[61932] = {true, true, false, false, true, true}, --Assassin's Scourge
	[61907] = {true, true, false, false, true, true}, --Assassin's Will
	[61930] = {true, true, false, false, true, true}, --Assassin's Will
	[25267] = {true, true, false, false, true, true}, --Concealed Weapon
	[33219] = {false, false, false, false, true, true}, --Corrode (pet)
	[51556] = {false, false, false, false, true, true}, --Corrode (pet)
	[36963] = {true, true, false, false, true, true}, --Crippling Grasp
	[36960] = {true, false, true, false, true, true}, --Crippling Grasp dot
	[36947] = {true, false, true, false, true, true}, --Debilitate
	[34838] = {true, true, false, false, true, true}, --Funnel Health
	[34851] = {true, true, false, false, true, true}, --Impale
	[36508] = {true, true, false, false, true, true}, --Incapacitating Strike
	[34843] = {true, true, false, false, true, true}, --Killers Blade
	[25494] = {true, true, false, false, true, true}, --Lotus Fan
	[35336] = {true, false, true, false, true, true}, --Lotus Fan dot
	[64001] = {true, false, true, false, true, true}, --Path of Darkness (Refreshing Path)
	[36901] = {true, true, false, false, true, true}, --Power Extraction
	[36891] = {true, true, false, false, true, true}, --Sap Essence
	[36514] = {true, true, false, false, true, true}, --Soul Harvest
	[35465] = {true, true, false, false, true, true}, --Soul Tether
	[35462] = {true, false, true, false, true, true}, --Soul Tether dot
	[25260] = {true, true, false, false, true, true}, --Surprise Attack
	[34835] = {true, true, false, false, true, true}, --Swallow Soul
	[36052] = {true, false, true, false, true, true}, --Twisting Path
	[36490] = {true, false, true, false, true, true}, --Veil of Blades
	[108936] = {false, false, false, false, true, true}, --Whirlwind (pet)
	[38268] = {true, true, false, false, true, true}, --Deep Slash
	[60921] = {true, true, false, false, true, true}, --Deep Slash
	[15829] = {true, true, false, true, true, true}, --Heavy Attack (1H+S)
	[15282] = {true, true, false, true, true, true}, --Heavy Attack (Medium, 1H+S)
	[38264] = {true, true, false, false, true, true}, --Heroic Slash
	[38406] = {true, true, false, false, true, true}, --Invasion
	[15435] = {true, true, false, true, true, true}, --Light Attack (1H+S)
	[28304] = {true, true, false, false, true, true}, --Low Slash
	[38250] = {true, true, false, false, true, true}, --Pierce Armor
	[38365] = {true, true, false, false, true, true}, --Power Bash
	[38452] = {true, true, false, false, true, true}, --Power Slam
	[28306] = {true, true, false, false, true, true}, --Puncture
	[38256] = {true, true, false, false, true, true}, --Ransack
	[38455] = {true, true, false, false, true, true}, --Reverberating Bash
	[28721] = {true, true, false, false, true, true}, --Shield Charge
	[38402] = {true, true, false, false, true, true}, --Shielded Assault
	[21970] = {true, true, false, false, true, true}, --Bash
	[21925] = {true, false, true, false, true, true}, --Diseased
	[21929] = {true, false, true, false, true, true}, --Poisoned
	[60230] = {true, true, false, false, true, true}, --Riposte
	[79025] = {true, false, true, false, true, true}, --Creeping Ravage Health
	[81275] = {true, true, false, false, true, true}, --Creeping Ravage Health (Crown Store)
	[79707] = {true, false, true, false, true, true}, --Ravage Health
	[81274] = {true, true, false, false, true, true}, --Ravage Health (Crown Store)
	[103626] = {true, true, false, false, true, true}, --Crushing Weapon
	[103572] = {true, true, false, false, true, true}, --Elemental Weapon
	[103485] = {true, true, false, false, true, true}, --Imbue Weapon
	[103880] = {true, true, false, false, true, true}, --Spell Orb (magic)
	[103881] = {true, true, false, false, true, true}, --Spell Orb (physical)
	[16212] = {true, false, true, true, true, true}, --Heavy Attack (Resto)
	[16145] = {true, true, false, true, true, true}, --Light Attack (Resto)
	[18718] = {true, true, false, false, true, true}, --Mages' Fury
	[19109] = {true, true, false, false, true, true}, --Endless Fury
	[19123] = {true, true, false, false, true, true}, --Magess' Wraith
	[23189] = {true, false, true, false, true, true}, --Lightning Splash
	[23202] = {true, false, true, false, true, true}, --Liquid Lightning
	[23208] = {true, false, true, false, true, true}, --Lightning Flood
	[23211] = {true, false, true, false, true, true}, --Lightning Form
	[23214] = {true, false, true, false, true, true}, --Boundless Storm
	[23232] = {true, false, true, false, true, true}, --Hurricane
	[23239] = {true, true, false, false, true, true}, --Streak
	[23428] = {true, false, true, false, true, true}, --Atronach Zap (Storm Atronach)
	[23659] = {true, true, false, false, true, true}, --Summon Storm Atronach
	[23664] = {true, true, false, false, true, true}, --Greater Storm Attronach
	[23667] = {true, true, false, false, true, true}, --Summon Charged Atronach
	[24327] = {true, true, false, false, true, true}, --Daedric Curse
	[24329] = {true, true, false, false, true, true}, --Daedric Prey
	[24331] = {true, true, false, false, true, true}, --Haunting Curse
	[24617] = {true, true, false, false, true, true}, --Summon Twilight Zap
	[24792] = {true, true, false, false, true, true}, --Overload Light Attack
	[24798] = {true, false, true, false, true, true}, --Overload Heavy Attack
	[24811] = {true, false, true, false, true, true}, --Power Overload Heavy
	[24829] = {true, false, true, false, true, true}, --Daedric Mines
	[24843] = {true, false, true, false, true, true}, --Daedric Tomb
	[25161] = {true, false, true, false, true, true}, --Daedric Minefield
	[27850] = {true, true, false, false, true, true}, --Familiar Melee (Unstable Familiar)
	[28027] = {true, true, false, false, true, true}, --Summon Twilight Kick
	[28309] = {true, true, false, false, true, true}, --Shattering Prison
	[29528] = {true, true, false, false, true, true}, --Headbutt (Unstable Clannfear)
	[29529] = {true, true, false, false, true, true}, --Tail Spike (Unstable Clannfear)
	[29809] = {true, true, false, false, true, true}, --Lightning Strike (Charged Atronach)
	[43714] = {true, true, false, false, true, true}, --Crystal Shard
	[45194] = {true, true, false, false, true, true}, --Implosion (Lightning)
	[46324] = {true, true, false, false, true, true}, --Crystal Fragments
	[46331] = {true, true, false, false, true, true}, --Crystal Blast
	[46743] = {true, true, false, false, true, true}, --Absorb Magicka
	[77186] = {true, false, true, false, true, true}, --Familiar Damage Pulse (Volatile Familiar)
	[80435] = {true, false, true, false, true, true}, --Suppression Field
	[82806] = {true, true, false, false, true, true}, --Implosion (Physical)
	[100118] = {true, true, false, false, true, true}, --Petrify (Rune Cage)
	[108844] = {true, false, true, false, true, true}, --Familiar Damage Pulse (Unstable Familiar)
	[114716] = {true, true, false, false, true, true}, --Crystal Fragments
	[117255] = {true, true, false, false, true, true}, --Volatile Familiar Melee
	[117273] = {true, true, false, false, true, true}, --Twilight Tormentor Zap
	[117274] = {true, true, false, false, true, true}, --Twilight Tormentor Kick
	[117320] = {true, true, false, false, true, true}, --Twillight Matriarch Kick
	[117321] = {true, true, false, false, true, true}, --Twillight Matriarch Zap
	[40317] = {true, false, true, false, true, true}, --Consuming Trap
	[40414] = {true, false, true, false, true, true}, --Shatter Soul
	[40420] = {true, false, true, false, true, true}, --Soul Assault
	[40328] = {true, false, true, false, true, true}, --Soul Splitting Trap
	[26800] = {true, true, false, false, true, true}, --Aurora Javelin
	[26804] = {true, true, false, false, true, true}, --Binding Javelin
	[44432] = {true, false, true, false, true, true}, --Biting Jabs
	[26794] = {true, false, true, false, true, true}, --Biting Jabs (splash)
	[26871] = {true, true, false, false, true, true}, --Blazing Spear
	[26879] = {true, false, true, false, true, true}, --Blazing Spear Pulse
	[44731] = {true, true, false, false, true, true}, --Burning Light
	[80170] = {true, true, false, false, true, true}, --Burning Light
	[22139] = {true, true, false, false, true, true}, --Crescent Sweep
	[62606] = {true, false, true, false, true, true}, --Crescent Sweep (dot)
	[22110] = {true, true, false, false, true, true}, --Dark Flare
	[22144] = {true, true, false, false, true, true}, --Empowering Sweep
	[62598] = {true, false, true, false, true, true}, --Empowering Sweep (dot)
	[22165] = {true, true, false, false, true, true}, --Explosive Charge
	[26859] = {true, true, false, false, true, true}, --Luminous Shards
	[95955] = {true, false, true, false, true, true}, --Luminous Shards (dot)
	[89828] = {true, true, false, false, true, true}, --Power of the Light (1st)
	[27567] = {false, false, false, false, false, false}, --Power of the Light (2nd)
	[44436] = {true, false, true, false, true, true}, --Puncturing Sweep
	[26799] = {true, false, true, false, true, true}, --Puncturing Sweep (splash)
	[89825] = {true, true, false, false, true, true}, --Purifying Light (1st)
	[27544] = {false, false, false, false, false, false}, --Purifying Light (2nd)
	[22138] = {true, false, true, false, true, true}, --Radial Sweep
	[62550] = {true, false, true, false, true, true}, --Radial Sweep
	[63956] = {true, false, true, false, true, true}, --Radiant Glory
	[63961] = {true, false, true, false, true, true}, --Radiant Oppression (dot)
	[22182] = {true, true, false, false, true, true}, --Radiant Ward
	[21732] = {true, true, false, false, true, true}, --Reflective Light
	[21734] = {true, false, true, false, true, true}, --Reflective Light (dot)
	[80172] = {true, false, true, false, true, true}, --Ritual of Retribution
	[100218] = {true, true, false, false, true, true}, --Solar Barrage
	[21759] = {true, false, true, false, true, true}, --Solar Disturbance
	[21756] = {true, false, true, false, true, true}, --Solar Prison
	[21726] = {true, true, false, false, true, true}, --Sun Fire
	[21728] = {true, false, true, false, true, true}, --Sun Fire (DoT)
	[22178] = {true, true, false, false, true, true}, --Sun Shield
	[15544] = {true, true, false, false, true, true}, --Toppling Charge
	[68729] = {true, true, false, false, true, true}, --Total Dark
	[22005] = {true, true, false, false, true, true}, --Unstable Core
	[21729] = {true, true, false, false, true, true}, --Vampires Bane
	[21731] = {true, false, true, false, true, true}, --Vampires Bane (dot)
	[83238] = {true, true, false, false, true, false}, --Berserker Rage
	[83216] = {true, true, false, false, true, false}, --Berserker Strike
	[38754] = {true, true, false, false, true, true}, --Brawler
	[38759] = {true, false, true, false, true, false}, --Brawler Bleed
	[38745] = {true, true, false, false, true, true}, --Carve
	[38747] = {true, false, true, false, true, false}, --Carve Bleed
	[20919] = {true, true, false, false, true, true}, --Cleave
	[31059] = {true, false, true, false, true, false}, --Cleave Bleed
	[28449] = {true, true, false, false, true, true}, --Critical Charge
	[38782] = {true, true, false, false, true, true}, --Critical Rush
	[38814] = {true, true, false, false, true, true}, --Dizzying Swing
	[38819] = {true, true, false, false, true, true}, --Executioner
	[17163] = {true, true, false, true, true, true}, --Heavy Attack (2H)
	[17162] = {true, true, false, true, true, true}, --Heavy Attack (Medium, 2H)
	[45431] = {true, false, true, false, true, false}, --Heavy Weapons Bleed
	[16037] = {true, true, false, true, true, true}, --Light Attack (2H)
	[83229] = {true, true, false, false, true, false}, --Onslaught
	[28302] = {true, true, false, false, true, true}, --Reverse Slash
	[38823] = {true, true, false, false, true, true}, --Reverse Slice
	[38827] = {true, true, false, false, true, true}, --Reverse Slice (2nd)
	[38792] = {true, true, false, false, true, true}, --Stampede
	[28279] = {true, true, false, false, true, true}, --Uppercut
	[38807] = {true, true, false, false, true, true}, --Wrecking Blow
	[42060] = {true, true, false, false, true, true}, --Inner Beast
	[42056] = {true, true, false, false, true, true}, --Inner Rage
	[80107] = {true, true, false, false, true, true}, --Shadow Silk (not synergy)
	[80129] = {true, true, false, false, true, true}, --Tangling Webs (not synergy)
	[38956] = {true, false, true, false, true, true}, --Accelerating Drain
	[38968] = {true, false, true, false, true, true}, --Baleful Mist
	[32625] = {true, false, true, false, true, true}, --Bat Swarm
	[38935] = {true, false, true, false, true, true}, --Clouding Swarm
	[38934] = {true, false, true, false, true, true}, --Devouring Swarm
	[32893] = {true, false, true, false, true, true}, --Drain Essence
	[38949] = {true, false, true, false, true, true}, --Invigorating Drain
	[87256] = {true, false, true, false, true, true}, --Arctic Blast
	[89128] = {true, true, false, false, true, true}, --Crushing Swipe (pet)
	[89220] = {true, true, false, false, true, true}, --Crushing Swipe (pet)
	[105907] = {true, true, false, false, true, true}, --Crushing Swipe (pet)
	[85999] = {true, true, false, false, true, true}, --Cutting Dive
	[94424] = {true, true, false, false, true, true}, --Deep Fissure
	[85995] = {true, true, false, false, true, true}, --Dive
	[101904] = {true, true, false, false, true, true}, --Fetcher Infection
	[88791] = {true, false, true, false, true, true}, --Gripping Shards
	[101944] = {true, true, false, false, true, true}, --Growing Swarm
	[92160] = {true, true, false, false, true, true}, --Guardian Savagery
	[91974] = {true, true, false, false, true, true}, --Guardian's Wrath (pet)
	[105921] = {true, true, false, false, true, true}, --Guardian's Wrath (pet)
	[88783] = {true, false, true, false, true, true}, --Impaling Shards
	[88860] = {true, false, true, false, true, true}, --Northern Storm
	[88863] = {true, true, false, false, true, true}, --Permafrost
	[94411] = {true, true, false, false, true, true}, --Scorch
	[86003] = {true, true, false, false, true, true}, --Screaming Cliff Racer
	[86247] = {true, false, true, false, true, true}, --Sleet Storm
	[94445] = {true, true, false, false, true, true}, --Subterranean Assault
	[101703] = {true, false, true, false, true, true}, --Swarm
	[89135] = {true, true, false, false, true, true}, --Swipe (pet)
	[89219] = {true, true, false, false, true, true}, --Swipe (pet)
	[105906] = {true, true, false, false, true, true}, --Swipe (pet)
	[88802] = {true, false, true, false, true, true}, --Winters Revenge
	[39109] = {true, true, false, false, true, true}, --Brutal Pounce
	[58864] = {true, true, false, false, true, true}, --Claws of Anguish
	[58879] = {true, true, false, false, true, true}, --Claws of Life
	[58880] = {true, false, true, false, true, true}, --Claws of Life (dot)
	[39107] = {true, true, false, false, true, true}, --Feral Pounce
	[80189] = {true, true, false, false, true, true}, --Gnash (Pact Leader)
	[80190] = {true, true, false, false, true, true}, --Gnash (Pact Leader)
	[32494] = {true, true, false, true, true, true}, --Heavy Attack (Splash)
	[32480] = {true, true, false, true, true, true}, --Heavy Attack Werewolf
	[58798] = {true, true, false, false, true, true}, --Howl of Agony
	[58742] = {true, true, false, false, true, true}, --Howl of Dispair
	[58856] = {true, false, true, false, false, true}, --Infection
	[58855] = {true, true, false, false, true, true}, --Infectious Claws
	[32464] = {true, true, false, true, true, true}, --Light Attack
	[80184] = {true, true, false, false, true, true}, --Lunge (Pact Leader)
	[58405] = {true, true, false, false, true, true}, --Piercing Howl
	[32645] = {true, true, false, false, true, true}, --Pounce
	[89147] = {true, false, true, false, true, false}, --Werewolf Berserker Bleed
	[89146] = {true, false, true, false, true, false}, --Werewolf Bleed
}

local AbilityData27 = {
	[40267] = {true, true, false, false, true, true}, --Anti-Cavalry Caltrops
	[38561] = {true, true, false, false, true, true}, --Caltrops
	[61493] = {true, true, false, false, true, true}, --Inevitable Detonation
	[61488] = {true, true, false, false, true, true}, --Magicka Detonation
	[61502] = {true, true, false, false, true, true}, --Proximity Detonation
	[40252] = {true, true, false, false, true, true}, --Razor Caltrops
	[40254] = {true, true, false, false, true, true}, --Razor Caltrops
	[38703] = {true, false, true, false, true, true}, --Acid Spray
	[38724] = {true, true, false, false, true, true}, --Acid Spray
	[38696] = {true, false, true, false, true, true}, --Arrow Barrage
	[38722] = {true, true, false, false, true, true}, --Arrow Spray
	[85462] = {true, true, false, false, true, true}, --Ballista
	[38723] = {true, true, false, false, true, true}, --Bombard
	[38669] = {true, true, false, false, true, true}, --Draining Shot
	[38690] = {true, false, true, false, true, true}, --Endless Hail
	[38687] = {true, true, false, false, true, true}, --Focused Aim
	[17173] = {true, true, false, true, true, true}, --Heavy Attack
	[17174] = {true, true, false, true, true, true}, --Heavy Attack
	[38685] = {true, true, false, false, true, true}, --Lethal Arrow
	[16688] = {true, true, false, true, true, true}, --Light Attack
	[38672] = {true, true, false, false, true, true}, --Magnum Shot
	[28869] = {true, true, false, false, true, true}, --Poison Arrow
	[44540] = {true, false, true, false, true, true}, --Poison Arrow
	[38660] = {true, true, false, false, true, true}, --Poison Injection
	[44549] = {true, false, true, false, true, true}, --Poison Injection
	[86563] = {true, false, true, false, true, true}, --Rapid Fire
	[28879] = {true, true, false, false, true, true}, --Scatter Shot
	[28882] = {true, true, false, false, true, true}, --Snipe
	[85260] = {true, false, true, false, true, true}, --Toxic Barrage
	[85261] = {true, false, true, false, true, true}, --Toxic Barrage
	[38645] = {true, true, false, false, true, true}, --Venom Arrow
	[44545] = {true, false, true, false, true, true}, --Venom Arrow
	[28877] = {true, false, true, false, true, true}, --Volley
	[46348] = {true, true, false, false, true, true}, --Crushing Shock
	[46350] = {true, true, false, false, true, true}, --Crushing Shock
	[46351] = {true, true, false, false, true, true}, --Crushing Shock
	[46356] = {true, true, false, false, true, true}, --Force Pulse
	[46357] = {true, true, false, false, true, true}, --Force Pulse
	[46358] = {true, true, false, false, true, true}, --Force Pulse
	[46340] = {true, true, false, false, true, true}, --Force Shock
	[46341] = {true, true, false, false, true, true}, --Force Shock
	[46343] = {true, true, false, false, true, true}, --Force Shock
	[20660] = {true, true, false, false, true, true}, --Burning Embers
	[44373] = {true, false, true, false, true, true}, --Burning Embers
	[20252] = {true, true, false, false, true, true}, --Burning Talons
	[31898] = {true, false, true, false, true, true}, --Burning Talons
	[20251] = {true, true, false, false, true, true}, --Choking Talons
	[17879] = {true, false, true, false, true, false}, --Corrosive Armor
	[20245] = {true, true, false, false, true, true}, --Dark Talons
	[32792] = {true, true, false, false, true, true}, --Deep Breath
	[32794] = {true, true, false, false, true, true}, --Deep Breath
	[32753] = {true, true, false, false, true, true}, --Dragon Fire Scale
	[29014] = {true, true, false, false, true, true}, --Dragon Leap
	[28995] = {true, false, true, false, true, true}, --Dragonknight Standard
	[32785] = {true, true, false, false, true, true}, --Draw Essence
	[32787] = {true, true, false, false, true, true}, --Draw Essence
	[20499] = {true, true, false, false, true, true}, --Empowering Chains
	[20930] = {true, true, false, false, true, true}, --Engulfing Flames
	[31104] = {true, false, true, false, true, true}, --Engulfing Flames
	[32711] = {true, false, true, false, true, true}, --Eruption
	[32714] = {true, true, false, false, true, true}, --Eruption
	[32716] = {true, true, false, false, true, true}, --Ferocious Leap
	[20917] = {true, true, false, false, true, true}, --Fiery Breath
	[31102] = {true, false, true, false, true, true}, --Fiery Breath
	[20492] = {true, true, false, false, true, true}, --Fiery Grip
	[20816] = {true, true, false, false, true, true}, --Flame Lash
	[61945] = {true, true, false, false, true, true}, --Flames of Oblivion
	[54931] = {true, true, false, false, true, true}, --Fossilize
	[20329] = {true, true, false, false, false, true}, --Hardened Armor
	[28969] = {true, true, false, false, true, true}, --Inferno
	[31837] = {true, true, false, false, true, true}, --Inhale
	[31842] = {true, true, false, false, true, true}, --Inhale
	[23806] = {true, true, false, false, true, true}, --Lava Whip
	[15959] = {true, false, true, false, true, true}, --Magma Armor
	[17875] = {true, false, true, false, true, true}, --Magma Shell
	[20805] = {true, true, false, false, true, true}, --Molten Whip
	[20944] = {true, true, false, false, true, true}, --Noxious Breath
	[31103] = {true, false, true, false, true, true}, --Noxious Breath
	[31820] = {true, true, false, false, true, true}, --Obsidian Shard
	[54918] = {true, true, false, false, true, true}, --Petrify
	[20824] = {true, true, false, false, true, true}, --Power Lash
	[20657] = {true, true, false, false, true, true}, --Searing Strike
	[44363] = {true, false, true, false, true, true}, --Searing Strike
	[32684] = {true, true, false, false, true, true}, --Shattering Rocks
	[32960] = {true, false, true, false, true, true}, --Shifting Standard
	[32964] = {true, false, true, false, true, true}, --Shifting Standard
	[20320] = {true, true, false, false, false, true}, --Spiked Armor
	[32948] = {true, false, true, false, true, true}, --Standard of Might
	[31816] = {true, true, false, false, true, true}, --Stone Giant
	[29032] = {true, true, false, false, true, true}, --Stonefist
	[32720] = {true, true, false, false, true, true}, --Take Flight
	[20496] = {true, true, false, false, true, true}, --Unrelenting Grip
	[20668] = {true, true, false, false, true, true}, --Venomous Claw
	[44369] = {true, false, true, false, true, true}, --Venomous Claw
	[20326] = {true, false, true, false, true, true}, --Volatile Armor
	[20324] = {true, true, false, false, false, true}, --Volatile Armor
	[62522] = {true, false, true, false, true, true}, --Blade Cloak
	[38845] = {true, true, false, false, true, true}, --Blood Craze
	[38847] = {true, true, false, false, true, true}, --Blood Craze
	[38848] = {true, false, true, false, true, false}, --Blood Craze Bleed
	[38846] = {true, false, true, false, true, true}, --Bloodthirst
	[62547] = {true, false, true, false, true, true}, --Deadly Cloak
	[28607] = {true, false, true, false, true, true}, --Flurry
	[38910] = {true, true, false, false, true, true}, --Flying Blade
	[17169] = {true, true, false, true, true, true}, --Heavy Attack
	[17170] = {true, true, false, true, true, true}, --Heavy Attack
	[18622] = {true, true, false, true, true, true}, --Heavy Attack (Dual Wield)
	[21157] = {true, true, false, false, true, true}, --Hidden Blade
	[85156] = {true, false, true, false, true, true}, --Lacerate
	[16499] = {true, true, false, true, true, true}, --Light Attack
	[62529] = {true, false, true, false, true, true}, --Quick Cloak
	[38857] = {true, false, true, false, true, true}, --Rapid Strikes
	[85192] = {true, false, true, false, true, true}, --Rend
	[38839] = {true, true, false, false, true, true}, --Rending Slashes
	[38840] = {true, true, false, false, true, true}, --Rending Slashes
	[38841] = {true, false, true, false, true, false}, --Rending Slashes Bleed
	[38914] = {true, true, false, false, true, true}, --Shrouded Daggers
	[68862] = {true, true, false, false, true, true}, --Shrouded Daggers
	[68864] = {true, true, false, false, true, true}, --Shrouded Daggers
	[38861] = {true, true, false, false, true, true}, --Steel Tornado
	[85182] = {true, true, false, false, true, true}, --Thrive in Chaos
	[45483] = {true, false, true, false, true, false}, --Twin Blade and Blunt Bleed
	[28379] = {true, true, false, false, true, true}, --Twin Slashes
	[35312] = {true, true, false, false, true, true}, --Twin Slashes
	[29293] = {true, false, true, false, true, false}, --Twin Slashes Bleed
	[38891] = {true, true, false, false, true, true}, --Whirling Blades
	[28591] = {true, true, false, false, true, true}, --Whirlwind
	[35713] = {true, true, false, false, true, true}, --Dawnbreaker
	[62305] = {true, true, false, false, true, true}, --Dawnbreaker
	[40158] = {true, true, false, false, true, true}, --Dawnbreaker of Smiting
	[62314] = {true, true, false, false, true, true}, --Dawnbreaker of Smiting
	[40161] = {true, true, false, false, true, true}, --Flawless Dawnbreaker
	[62310] = {true, true, false, false, true, true}, --Flawless Dawnbreaker
	[40375] = {true, true, false, false, true, true}, --Lightweight Beast Trap
	[40376] = {true, true, false, false, true, true}, --Lightweight Beast Trap
	[40385] = {true, true, false, false, true, true}, --Rearming Trap
	[40389] = {true, true, false, false, true, true}, --Rearming Trap
	[40392] = {true, true, false, false, true, true}, --Rearming Trap
	[35721] = {true, true, false, false, true, true}, --Silver Bolts
	[40336] = {true, true, false, false, true, true}, --Silver Leash
	[40300] = {true, true, false, false, true, true}, --Silver Shards
	[40452] = {true, true, false, false, true, true}, --Structured Entropy
	[35754] = {true, true, false, false, true, true}, --Trap Beast
	[35756] = {true, true, false, false, true, true}, --Trap Beast
	[62951] = {true, false, true, false, true, true}, --Blockade of Frost
	[83685] = {true, false, true, false, true, true}, --Eye of Frost
	[38989] = {true, true, false, false, true, true}, --Frost Clench
	[62702] = {true, false, true, false, true, true}, --Frost Clench
	[28798] = {true, true, false, false, true, true}, --Frost Impulse
	[39163] = {true, true, false, false, true, true}, --Frost Pulsar
	[38970] = {true, true, false, false, true, true}, --Frost Reach
	[62712] = {true, false, true, false, true, true}, --Frost Reach
	[39151] = {true, true, false, false, true, true}, --Frost Ring
	[29078] = {true, true, false, false, true, true}, --Frost Touch
	[62692] = {true, false, true, false, true, true}, --Frost Touch
	[18405] = {true, true, false, true, true, true}, --Heavy Attack
	[18406] = {true, true, false, true, true, true}, --Heavy Attack
	[83629] = {true, false, true, false, true, true}, --Ice Storm
	[85129] = {true, false, true, false, true, true}, --Icy Rage
	[16277] = {true, true, false, true, true, true}, --Light Attack
	[39071] = {true, false, true, false, true, true}, --Unstable Wall of Frost
	[39072] = {true, true, false, false, true, true}, --Unstable Wall of Frost
	[62931] = {true, false, true, false, true, true}, --Wall of Frost
	[46743] = {true, true, false, false, true, true}, --Absorb Magicka
	[62912] = {true, false, true, false, true, true}, --Blockade of Fire
	[83683] = {true, false, true, false, true, true}, --Eye of Flame
	[85127] = {true, false, true, false, true, true}, --Fiery Rage
	[62668] = {true, false, true, false, true, true}, --Fire Clench
	[28794] = {true, true, false, false, true, true}, --Fire Impulse
	[39149] = {true, true, false, false, true, true}, --Fire Ring
	[83626] = {true, false, true, false, true, true}, --Fire Storm
	[62648] = {true, false, true, false, true, true}, --Fire Touch
	[38985] = {true, true, false, false, true, true}, --Flame Clench
	[39162] = {true, true, false, false, true, true}, --Flame Pulsar
	[38944] = {true, true, false, false, true, true}, --Flame Reach
	[62682] = {true, false, true, false, true, true}, --Flame Reach
	[29073] = {true, true, false, false, true, true}, --Flame Touch
	[15385] = {true, true, false, true, true, true}, --Heavy Attack
	[16321] = {true, true, false, true, true, true}, --Heavy Attack
	[16165] = {true, true, false, true, true, true}, --Light Attack
	[39054] = {true, false, true, false, true, true}, --Unstable Wall of Fire
	[39056] = {true, true, false, false, true, true}, --Unstable Wall of Fire
	[62896] = {true, false, true, false, true, true}, --Wall of Fire
	[46746] = {true, true, false, false, true, true}, --Absorb Stamina
	[107203] = {true, true, true, false, true, true}, --Arms of Relequen
	[17904] = {true, true, false, false, true, true}, --Befouled Weapon
	[17899] = {true, true, false, false, true, true}, --Charged Weapon
	[46749] = {true, true, false, false, true, true}, --Damage Health
	[93307] = {true, true, false, false, false, true}, --Defiler
	[97883] = {true, false, true, false, false, true}, --Domihaus (fire)
	[60972] = {true, false, true, false, false, true}, --Fiery Breath
	[60973] = {true, true, false, false, false, true}, --Fiery Jaws
	[17895] = {true, true, false, false, true, true}, --Fiery Weapon
	[17897] = {true, true, false, false, true, true}, --Frozen Weapon
	[84502] = {true, false, true, false, false, true}, --Grothdarr
	[80561] = {true, false, true, false, false, true}, --Iceheart
	[109086] = {true, true, true, false, true, true}, --Ideal Arms of Relequen
	[80525] = {true, false, true, false, false, true}, --Illambris (fire)
	[80526] = {true, false, true, false, false, true}, --Illambris (lightning)
	[83409] = {true, true, false, false, false, true}, --Infernal Guardian
	[60974] = {true, true, false, false, false, true}, --Jagged Claw
	[80565] = {true, false, true, false, false, true}, --Kra'gh
	[28919] = {true, true, false, false, true, true}, --Life Drain
	[107094] = {true, false, true, false, false, true}, --Mantle of Siroria
	[59498] = {true, false, true, false, false, true}, --Mephala's Web
	[59593] = {true, true, false, false, false, true}, --Nerien'eth
	[17902] = {true, true, false, false, true, true}, --Poisoned Weapon
	[40337] = {true, true, false, false, true, true}, --Prismatic Weapon
	[80606] = {true, true, false, false, false, true}, --Selene
	[80544] = {true, true, false, false, false, true}, --Sellistrix
	[80980] = {true, true, false, false, false, true}, --Shadowrend (base attack)
	[80989] = {true, true, false, false, false, true}, --Shadowrend (tail sweep)
	[80522] = {true, false, true, false, false, true}, --Stormfist (lightning)
	[80521] = {true, true, false, false, false, true}, --Stormfist (physical)
	[80865] = {true, true, false, false, false, true}, --Tremorscale
	[61273] = {true, true, false, false, false, true}, --Valkyn Skoria (splash)
	[59596] = {true, true, false, false, false, true}, --Valkyn Skoria (target hit)
	[80490] = {true, true, false, false, false, true}, --Velidreth
	[113627] = {true, true, false, false, true, true}, --Virulent Shot
	[102136] = {true, false, true, false, false, true}, --Zaan
	[62990] = {true, false, true, false, true, true}, --Blockade of Storms
	[83687] = {true, false, true, false, true, true}, --Eye of Lightning
	[18396] = {true, false, true, true, true, true}, --Heavy Attack (Shock)
	[18350] = {true, true, false, true, true, true}, --Light Attack
	[38993] = {true, true, false, false, true, true}, --Shock Clench
	[62733] = {true, false, true, false, true, true}, --Shock Clench
	[62734] = {true, true, false, false, true, true}, --Shock Clench Explosion
	[28799] = {true, true, false, false, true, true}, --Shock Impulse
	[19277] = {true, true, false, true, true, true}, --Shock Pulse
	[38978] = {true, true, false, false, true, true}, --Shock Reach
	[62745] = {true, false, true, false, true, true}, --Shock Reach
	[39153] = {true, true, false, false, true, true}, --Shock Ring
	[29089] = {true, true, false, false, true, true}, --Shock Touch
	[62722] = {true, false, true, false, true, true}, --Shock Touch
	[39167] = {true, true, false, false, true, true}, --Storm Pulsar
	[83631] = {true, false, true, false, true, true}, --Thunder Storm
	[85131] = {true, false, true, false, true, true}, --Thunderous Rage
	[45505] = {true, false, true, true, true, double}, --Tri Focus
	[39079] = {true, false, true, false, true, true}, --Unstable Wall of Storms
	[39080] = {true, true, false, false, true, true}, --Unstable Wall of Storms
	[62971] = {true, false, true, false, true, true}, --Wall of Storms
	[40457] = {true, true, false, false, true, true}, --Degeneration
	[28567] = {true, true, false, false, true, true}, --Entropy
	[31635] = {true, true, false, false, true, true}, --Fire Rune
	[63454] = {true, true, false, false, true, true}, --Ice Comet
	[63457] = {true, true, false, false, true, true}, --Ice Comet
	[17912] = {true, true, false, false, true, true}, --Meteor
	[63429] = {true, true, false, false, true, true}, --Meteor
	[40468] = {true, true, false, false, true, true}, --Scalding Rune
	[40469] = {true, true, false, false, true, true}, --Scalding Rune
	[63471] = {true, true, false, false, true, true}, --Shooting Star
	[63474] = {true, true, false, false, true, true}, --Shooting Star
	[40473] = {true, true, false, false, true, true}, --Volcanic Rune
	[117854] = {true, false, true, false, true, true}, --Avid Boneyard
	[115608] = {true, true, false, false, true, true}, --Blastbones
	[117715] = {true, true, false, false, true, true}, --Blighted Blastbones
	[115254] = {true, false, true, false, true, true}, --Boneyard
	[115115] = {true, true, false, false, true, true}, --Death Scythe
	[114461] = {true, true, false, false, true, true}, --Deathbolt
	[122774] = {true, true, false, false, true, true}, --Deathbolt
	[118746] = {true, true, false, false, true, true}, --Deathbolt
	[124468] = {true, true, false, false, true, true}, --Deathbolt
	[118766] = {true, false, true, false, true, true}, --Detonating Siphon
	[123082] = {true, true, false, false, true, true}, --Detonating Siphon
	[114108] = {true, true, false, false, true, true}, --Flame Skull
	[123683] = {true, true, false, false, true, true}, --Flame Skull
	[123685] = {true, true, false, false, true, true}, --Flame Skull
	[122178] = {true, false, true, false, true, true}, --Frozen Colossus
	[122392] = {true, false, true, false, true, true}, --Glacial Colossus
	[118223] = {true, false, true, false, true, true}, --Hungry Scythe
	[118011] = {true, false, true, false, true, true}, --Mystic Siphon
	[122399] = {true, false, true, false, true, true}, --Pestilent Colossus
	[122400] = {true, false, true, false, true, true}, --Pestilent Colossus
	[122401] = {true, false, true, false, true, true}, --Pestilent Colossus
	[118289] = {true, false, true, false, true, true}, --Ravenous Goliath
	[117637] = {true, true, false, false, true, true}, --Ricochet Skull
	[123718] = {true, true, false, false, true, true}, --Ricochet Skull
	[123719] = {true, true, false, false, true, true}, --Ricochet Skull
	[123722] = {true, true, false, false, true, true}, --Ricochet Skull
	[123729] = {true, true, false, false, true, true}, --Ricochet Skull
	[118226] = {true, true, false, false, true, true}, --Ruinous Scythe
	[116410] = {true, false, true, false, true, true}, --Shocking Siphon
	[117757] = {true, true, false, false, true, true}, --Stalking Blastbones
	[117809] = {true, false, true, false, true, true}, --Unnerving Boneyard
	[117624] = {true, true, false, false, true, true}, --Venom Skull
	[123699] = {true, true, false, false, true, true}, --Venom Skull
	[123704] = {true, true, false, false, true, true}, --Venom Skull
	[25485] = {true, true, false, false, true, true}, --Ambush
	[33386] = {true, true, false, false, true, true}, --Assassin's Blade
	[61932] = {true, true, false, false, true, true}, --Assassin's Scourge
	[61907] = {true, true, false, false, true, true}, --Assassin's Will
	[61930] = {true, true, false, false, true, true}, --Assassin's Will
	[25267] = {true, true, false, false, true, true}, --Concealed Weapon
	[51556] = {true, true, false, false, true, true}, --Corrosive Arrow
	[123945] = {true, true, false, false, true, true}, --Corrosive Flurry
	[108936] = {true, true, false, false, true, true}, --Corrosive Slash
	[33219] = {true, true, false, false, true, true}, --Corrosive Strike
	[33333] = {true, false, true, false, true, true}, --Cripple
	[36960] = {true, false, true, false, true, true}, --Crippling Grasp
	[36963] = {true, true, false, false, true, true}, --Crippling Grasp
	[33398] = {true, true, false, false, true, true}, --Death Stroke
	[36947] = {true, false, true, false, true, true}, --Debilitate
	[33316] = {true, true, false, false, true, true}, --Drain Power
	[34838] = {true, true, false, false, true, true}, --Funnel Health
	[34851] = {true, true, false, false, true, true}, --Impale
	[36508] = {true, true, false, false, true, true}, --Incapacitating Strike
	[34843] = {true, true, false, false, true, true}, --Killer's Blade
	[25494] = {true, true, false, false, true, true}, --Lotus Fan
	[35336] = {true, false, true, false, true, true}, --Lotus Fan
	[64001] = {true, false, true, false, true, true}, --Path of Darkness (Refreshing Path)
	[36901] = {true, true, false, false, true, true}, --Power Extraction
	[36891] = {true, true, false, false, true, true}, --Sap Essence
	[36514] = {true, true, false, false, true, true}, --Soul Harvest
	[25863] = {true, true, false, false, true, true}, --Soul Shred
	[35460] = {true, true, false, false, true, true}, --Soul Tether
	[35462] = {true, false, true, false, true, true}, --Soul Tether
	[35465] = {true, true, false, false, true, true}, --Soul Tether
	[33291] = {true, true, false, false, true, true}, --Strife
	[25260] = {true, true, false, false, true, true}, --Surprise Attack
	[34835] = {true, true, false, false, true, true}, --Swallow Soul
	[18346] = {true, true, false, false, true, true}, --Teleport Strike
	[36052] = {true, false, true, false, true, true}, --Twisting Path
	[36490] = {true, false, true, false, true, true}, --Veil of Blades
	[25255] = {true, true, false, false, true, true}, --Veiled Strike
	[38268] = {true, true, false, false, true, true}, --Deep Slash
	[60921] = {true, true, false, false, true, true}, --Deep Slash
	[15282] = {true, true, false, true, true, true}, --Heavy Attack
	[15829] = {true, true, false, true, true, true}, --Heavy Attack
	[38264] = {true, true, false, false, true, true}, --Heroic Slash
	[38406] = {true, true, false, false, true, true}, --Invasion
	[15435] = {true, true, false, true, true, true}, --Light Attack
	[28304] = {true, true, false, false, true, true}, --Low Slash
	[38250] = {true, true, false, false, true, true}, --Pierce Armor
	[28365] = {true, true, false, false, true, true}, --Power Bash
	[38365] = {true, true, false, false, true, true}, --Power Bash
	[38452] = {true, true, false, false, true, true}, --Power Slam
	[28306] = {true, true, false, false, true, true}, --Puncture
	[38256] = {true, true, false, false, true, true}, --Ransack
	[38455] = {true, true, false, false, true, true}, --Reverberating Bash
	[28721] = {true, true, false, false, true, true}, --Shield Charge
	[38402] = {true, true, false, false, true, true}, --Shielded Assault
	[21970] = {true, true, false, false, true, true}, --Bash
	[21925] = {true, false, true, false, true, true}, --Diseased
	[60230] = {true, true, false, false, true, true}, --Riposte
	[79025] = {true, false, true, false, true, true}, --Creeping Ravage Health
	[81275] = {true, true, false, false, true, true}, --Creeping Ravage Health (Crown Store)
	[79707] = {true, false, true, false, true, true}, --Ravage Health
	[81274] = {true, true, false, false, true, true}, --Ravage Health (Crown Store)
	[103880] = {true, true, false, false, true, true}, --Spell Orb (magic)
	[103881] = {true, true, false, false, true, true}, --Spell Orb (physical)
	[103626] = {true, true, false, false, true, true}, --Crushing Weapon
	[103572] = {true, true, false, false, true, true}, --Elemental Weapon
	[103485] = {true, true, false, false, true, true}, --Imbue Weapon
	[16212] = {true, false, true, true, true, true}, --Heavy Attack
	[16145] = {true, true, false, true, true, true}, --Light Attack
	[23428] = {true, false, true, false, true, true}, --Atronach Zap
	[23214] = {true, false, true, false, true, true}, --Boundless Storm
	[23667] = {true, true, false, false, true, true}, --Charged Atronach Impact
	[46331] = {true, true, false, false, true, true}, --Crystal Blast
	[46333] = {true, true, false, false, true, true}, --Crystal Blast
	[46324] = {true, true, false, false, true, true}, --Crystal Fragments
	[114716] = {true, true, false, false, true, true}, --Crystal Fragments
	[43714] = {true, true, false, false, true, true}, --Crystal Shard
	[44507] = {true, true, false, false, true, true}, --Daedric Curse
	[24327] = {true, true, false, false, true, true}, --Daedric Curse
	[25161] = {true, false, true, false, true, true}, --Daedric Minefield
	[24829] = {true, false, true, false, true, true}, --Daedric Mines
	[24329] = {true, true, false, false, true, true}, --Daedric Prey
	[44511] = {true, true, false, false, true, true}, --Daedric Prey
	[24843] = {true, false, true, false, true, true}, --Daedric Tomb
	[19109] = {true, true, false, false, true, true}, --Endless Fury
	[114798] = {true, false, true, true, true, true}, --Energy Overload Heavy Attack
	[114773] = {true, true, false, true, true, true}, --Energy Overload Light Attack
	[77186] = {true, false, true, false, true, true}, --Familiar Damage Pulse
	[108844] = {true, false, true, false, true, true}, --Familiar Damage Pulse
	[27850] = {true, true, false, false, true, true}, --Familiar Melee
	[23664] = {true, true, false, false, true, true}, --Greater Storm Atronach Impact
	[24331] = {true, true, false, false, true, true}, --Haunting Curse
	[44515] = {true, true, false, false, true, true}, --Haunting Curse
	[29528] = {true, true, false, false, true, true}, --Headbutt
	[23232] = {true, false, true, false, true, true}, --Hurricane
	[45194] = {true, true, false, false, true, true}, --Implosion (Lightning)
	[82806] = {true, true, false, false, true, true}, --Implosion (Physical)
	[23208] = {true, false, true, false, true, true}, --Lightning Flood
	[23211] = {true, false, true, false, true, true}, --Lightning Form
	[23189] = {true, false, true, false, true, true}, --Lightning Splash
	[29809] = {true, true, false, false, true, true}, --Lightning Strike
	[23202] = {true, false, true, false, true, true}, --Liquid Lightning
	[18718] = {true, true, false, false, true, true}, --Mages' Fury
	[19123] = {true, true, false, false, true, true}, --Mages' Wrath
	[24798] = {true, false, true, true, true, true}, --Overload Heavy Attack
	[24792] = {true, true, false, true, true, true}, --Overload Light Attack
	[24811] = {true, false, true, true, true, true}, --Power Overload Heavy Attack
	[114769] = {true, true, false, true, true, true}, --Power Overload Light Attack
	[100118] = {true, true, false, false, true, true}, --Rune Cage
	[28309] = {true, true, false, false, true, true}, --Shattering Prison
	[23659] = {true, true, false, false, true, true}, --Storm Atronach Impact
	[23239] = {true, true, false, false, true, true}, --Streak
	[28027] = {true, true, false, false, true, true}, --Summon Twilight Kick
	[24617] = {true, true, false, false, true, true}, --Summon Twilight Zap
	[80435] = {true, false, true, false, true, true}, --Suppression Field
	[29529] = {true, true, false, false, true, true}, --Tail Spike
	[117320] = {true, true, false, false, true, true}, --Twilight Matriarch Kick
	[117321] = {true, true, false, false, true, true}, --Twilight Matriarch Zap
	[117273] = {true, true, false, false, true, true}, --Twilight Tormentor Kick
	[117274] = {true, true, false, false, true, true}, --Twilight Tormentor Zap
	[117255] = {true, true, false, false, true, true}, --Volatile Familiar Melee
	[40317] = {true, false, true, false, true, true}, --Consuming Trap
	[40414] = {true, false, true, false, true, true}, --Shatter Soul
	[40420] = {true, false, true, false, true, true}, --Soul Assault
	[40328] = {true, false, true, false, true, true}, --Soul Splitting Trap
	[39270] = {true, false, true, false, true, true}, --Soul Strike
	[26768] = {true, false, true, false, true, true}, --Soul Trap
	[18084] = {true, false, true, false, true, true}, --Burning
	[21481] = {true, true, false, false, true, true}, --Chill
	[21487] = {true, false, true, false, true, true}, --Concussion
	[21929] = {true, false, true, false, true, true}, --Poisoned
	[26800] = {true, true, false, false, true, true}, --Aurora Javelin
	[26411] = {false, false, false, false, false, false}, --Backlash
	[89821] = {true, true, false, false, true, true}, --Backlash
	[26804] = {true, true, false, false, true, true}, --Binding Javelin
	[26794] = {true, false, true, false, true, true}, --Biting Jabs
	[44432] = {true, false, true, false, true, true}, --Biting Jabs
	[26871] = {true, false, true, false, true, true}, --Blazing Spear
	[26879] = {true, false, true, false, true, true}, --Blazing Spear
	[44731] = {true, true, false, false, true, true}, --Burning Light
	[80170] = {true, true, false, false, true, true}, --Burning Light
	[22139] = {true, true, false, false, true, true}, --Crescent Sweep
	[62606] = {true, true, false, false, true, true}, --Crescent Sweep
	[22110] = {true, true, false, false, true, true}, --Dark Flare
	[68657] = {true, true, false, false, true, true}, --Eclipse
	[22144] = {true, true, false, false, true, true}, --Empowering Sweep
	[62598] = {true, false, true, false, true, true}, --Empowering Sweep
	[22165] = {true, true, false, false, true, true}, --Explosive Charge
	[22155] = {true, true, false, false, true, true}, --Focused Charge
	[26859] = {true, false, true, false, true, true}, --Luminous Shards
	[95955] = {true, false, true, false, true, true}, --Luminous Shards
	[21753] = {true, false, true, false, true, true}, --Nova
	[26158] = {true, true, false, false, true, true}, --Piercing Javelin
	[27567] = {false, false, false, false, false, false}, --Power of the Light
	[89828] = {true, true, false, false, true, true}, --Power of the Light
	[26116] = {true, false, true, false, true, true}, --Puncturing Strikes
	[44426] = {true, false, true, false, true, true}, --Puncturing Strikes
	[26799] = {true, false, true, false, true, true}, --Puncturing Sweep
	[44436] = {true, false, true, false, true, true}, --Puncturing Sweep
	[27544] = {false, false, false, false, false, false}, --Purifying Light
	[89825] = {true, true, false, false, true, true}, --Purifying Light
	[63952] = {true, false, true, false, true, true}, --Radiant Destruction
	[63956] = {true, false, true, false, true, true}, --Radiant Glory
	[63961] = {true, false, true, false, true, true}, --Radiant Oppression
	[22182] = {true, true, false, false, true, true}, --Radiant Ward
	[21732] = {true, true, false, false, true, true}, --Reflective Light
	[21734] = {true, false, true, false, true, true}, --Reflective Light
	[80172] = {true, false, true, false, true, true}, --Ritual of Retribution
	[100218] = {true, false, true, false, true, true}, --Solar Barrage
	[22057] = {true, true, false, false, true, true}, --Solar Flare
	[21756] = {true, false, true, false, true, true}, --Solar Prison
	[26192] = {true, false, true, false, true, true}, --Spear Shards
	[95931] = {true, false, true, false, true, true}, --Spear Shards
	[21726] = {true, true, false, false, true, true}, --Sun Fire
	[21728] = {true, false, true, false, true, true}, --Sun Fire
	[22178] = {true, true, false, false, true, true}, --Sun Shield
	[15544] = {true, true, false, false, true, true}, --Toppling Charge
	[68729] = {true, true, false, false, true, true}, --Total Dark
	[100210] = {true, true, false, false, true, true}, --Unstable Core
	[22005] = {true, true, false, false, true, true}, --Unstable Core
	[21729] = {true, true, false, false, true, true}, --Vampire's Bane
	[21731] = {true, false, true, false, true, true}, --Vampire's Bane
	[83238] = {true, true, false, false, true, false}, --Berserker Rage
	[83216] = {true, true, false, false, true, false}, --Berserker Strike
	[38754] = {true, true, false, false, true, true}, --Brawler
	[38745] = {true, true, false, false, true, true}, --Carve
	[38747] = {true, false, true, false, true, false}, --Carve Bleed
	[20919] = {true, true, false, false, true, true}, --Cleave
	[28449] = {true, true, false, false, true, true}, --Critical Charge
	[38782] = {true, true, false, false, true, true}, --Critical Rush
	[38814] = {true, true, false, false, true, true}, --Dizzying Swing
	[38819] = {true, true, false, false, true, true}, --Executioner
	[45445] = {true, true, false, true, true, double}, --Forceful
	[17162] = {true, true, false, true, true, true}, --Heavy Attack
	[17163] = {true, true, false, true, true, true}, --Heavy Attack
	[45431] = {true, false, true, false, true, false}, --Heavy Weapons Bleed
	[16037] = {true, true, false, true, true, true}, --Light Attack
	[83229] = {true, true, false, false, true, false}, --Onslaught
	[28302] = {true, true, false, false, true, true}, --Reverse Slash
	[38823] = {true, true, false, false, true, true}, --Reverse Slice
	[38827] = {true, true, false, false, true, double}, --Reverse Slice
	[38792] = {true, true, false, false, true, true}, --Stampede
	[28279] = {true, true, false, false, true, true}, --Uppercut
	[38807] = {true, true, false, false, true, true}, --Wrecking Blow
	[42060] = {true, true, false, false, true, true}, --Inner Beast
	[39475] = {true, true, false, false, true, true}, --Inner Fire
	[42056] = {true, true, false, false, true, true}, --Inner Rage
	[42029] = {true, true, false, false, true, true}, --Mystic Orb
	[39299] = {true, true, false, false, true, true}, --Necrotic Orb
	[80107] = {true, true, false, false, true, true}, --Shadow Silk
	[42141] = {true, true, false, false, true, true}, --Spiked Bone Shield
	[80129] = {true, true, false, false, true, true}, --Tangling Webs
	[80083] = {true, false, true, false, true, true}, --Trapping Webs
	[38956] = {true, false, true, false, true, true}, --Accelerating Drain
	[38968] = {true, false, true, false, true, true}, --Baleful Mist
	[32625] = {true, false, true, false, true, true}, --Bat Swarm
	[38935] = {true, false, true, false, true, true}, --Clouding Swarm
	[38934] = {true, false, true, false, true, true}, --Devouring Swarm
	[32893] = {true, false, true, false, true, true}, --Drain Essence
	[38949] = {true, false, true, false, true, true}, --Invigorating Drain
	[88163] = {true, true, false, false, true, true}, --Materialize
	[87256] = {true, false, true, false, true, true}, --Arctic Blast
	[89128] = {true, true, false, false, true, true}, --Crushing Swipe
	[105907] = {true, true, false, false, true, true}, --Crushing Swipe
	[89220] = {true, true, false, false, true, true}, --Crushing Swipe
	[93175] = {true, true, false, false, true, true}, --Crystallized Slab
	[85999] = {true, true, false, false, true, true}, --Cutting Dive
	[94424] = {true, true, false, false, true, true}, --Deep Fissure
	[85995] = {true, true, false, false, true, true}, --Dive
	[101904] = {true, false, true, false, true, true}, --Fetcher Infection
	[108949] = {true, false, true, false, true, true}, --Frozen Device
	[108948] = {true, false, true, false, true, true}, --Frozen Gate
	[108950] = {true, false, true, false, true, true}, --Frozen Retreat
	[88791] = {true, false, true, false, true, true}, --Gripping Shards
	[101944] = {true, false, true, false, true, true}, --Growing Swarm
	[101948] = {true, false, true, false, true, true}, --Growing Swarm
	[92160] = {true, true, false, false, true, true}, --Guardian's Savagery
	[91974] = {true, true, false, false, true, true}, --Guardian's Wrath
	[105921] = {true, true, false, false, true, true}, --Guardian's Wrath
	[88783] = {true, false, true, false, true, true}, --Impaling Shards
	[88860] = {true, false, true, false, true, true}, --Northern Storm
	[88863] = {true, true, false, false, true, true}, --Permafrost
	[94411] = {true, true, false, false, true, true}, --Scorch
	[86003] = {true, true, false, false, true, true}, --Screaming Cliff Racer
	[86247] = {true, false, true, false, true, true}, --Sleet Storm
	[94445] = {true, true, false, false, true, true}, --Subterranean Assault
	[101703] = {true, false, true, false, true, true}, --Swarm
	[89135] = {true, true, false, false, true, true}, --Swipe
	[105906] = {true, true, false, false, true, true}, --Swipe
	[89219] = {true, true, false, false, true, true}, --Swipe
	[88802] = {true, false, true, false, true, true}, --Winters Revenge
	[39109] = {true, true, false, false, true, true}, --Brutal Pounce
	[61369] = {true, true, false, false, true, true}, --Brutal Pounce
	[58864] = {true, true, false, false, true, true}, --Claws of Anguish
	[58865] = {true, false, true, false, true, true}, --Claws of Anguish
	[58879] = {true, true, false, false, true, true}, --Claws of Life
	[58880] = {true, false, true, false, true, true}, --Claws of Life
	[39107] = {true, true, false, false, true, true}, --Feral Pounce
	[80189] = {true, true, false, false, true, true}, --Gnash
	[80190] = {true, true, false, false, true, true}, --Gnash
	[32479] = {true, true, false, false, true, true}, --Heavy Attack
	[32494] = {true, true, false, false, true, true}, --Heavy Attack
	[32480] = {true, true, false, false, true, true}, --Heavy Attack Werewolf
	[58798] = {true, true, false, false, true, true}, --Howl of Agony
	[58742] = {true, true, false, false, true, true}, --Howl of Despair
	[58855] = {true, true, false, false, true, true}, --Infectious Claws
	[58856] = {true, false, true, false, true, true}, --Infectious Claws
	[32464] = {true, true, false, true, true, true}, --Light Attack
	[80184] = {true, true, false, false, true, true}, --Lunge
	[58405] = {true, true, false, false, true, true}, --Piercing Howl
	[32645] = {true, true, false, false, true, true}, --Pounce
	[89147] = {true, false, true, false, true, false}, --Werewolf Berserker Bleed
	[89146] = {true, false, true, false, true, false}, --Werewolf Bleed
}

function GetConstellationAbilityData()

	if GetAPIVersion() < 100027 then 
	
		return AbilityData
		
	else 
	
		return AbilityData27
		
	end
end