-- isAffectedby = {Master-at-Arms, Thaumaturge, Staff/Weapon Expert, Elfborn/Precise Strikes}  (only pet skills or skills that can't crit are not affected by elfborn)
-- list is at https://docs.google.com/spreadsheets/d/1k9aDTz-kv-zrnUmAkVnX3bHQbF-QTdAhDtsfbu8zJkA/edit?usp=sharing

local AbilityData = {
	[46431] = {false, true, false, true}, --Anti-Calvary Caltrops
	[63295] = {false, false, false, true}, --Inevitable Detonation
	[63304] = {false, false, false, true}, --Proximity Detonation
	[46465] = {false, false, false, true}, --Razor Caltrops
	[46478] = {false, false, false, true}, --Razor Caltrops
	[46464] = {false, true, false, true}, --Razor Caltrops dot
	[46477] = {false, true, false, true}, --Razor Caltrops dot
	[40791] = {true, false, false, true}, --Acid Spray
	[40790] = {false, true, false, true}, --Acid Spray (dot)
	[40945] = {false, true, false, true}, --Arrow Barrage
	[85462] = {true, false, false, true}, --Ballista
	[86621] = {true, false, false, true}, --Ballista
	[40780] = {true, false, false, true}, --Bombard
	[40883] = {true, false, false, true}, --Draining Shot
	[40933] = {false, true, false, true}, --Endless Hail
	[40907] = {true, false, false, true}, --Focused Aim
	[17174] = {true, false, true, true}, --Heavy Attack (Bow)
	[17173] = {true, false, true, true}, --Heavy Attack (Bow), full
	[40897] = {true, false, false, true}, --Lethal Arrow
	[16688] = {true, false, true, true}, --Light Attack (Bow)
	[40869] = {true, false, false, true}, --Magnum Shot
	[40842] = {true, false, false, true}, --Poison Injection
	[44552] = {false, true, false, true}, --Poison Injection (dot)
	[86604] = {false, true, false, true}, --Toxic Barrage
	[86605] = {false, true, false, true}, --Toxic Barrage (dot)
	[40823] = {true, false, false, true}, --Venom Arrow
	[44548] = {false, true, false, true}, --Venom Arrow (dot)
	[62924] = {false, true, false, true}, --Blockade of Fire
	[62966] = {false, true, false, true}, --Blockade of Frost
	[63005] = {false, true, false, true}, --Blockade of Storms
	[18084] = {false, true, false, true}, --Burning
	[21481] = {false, true, false, true}, --Chill
	[21487] = {false, true, false, true}, --Concussion
	[48971] = {true, false, false, true}, --Crushing Shock (Fire)
	[48972] = {true, false, false, true}, --Crushing Shock (Frost)
	[48973] = {true, false, false, true}, --Crushing Shock (Shock)
	[68458] = {false, true, false, true}, --Deep Freeze
	[86541] = {false, true, false, true}, --Eye of Flame
	[86547] = {false, true, false, true}, --Eye of Frost
	[86553] = {false, true, false, true}, --Eye of Lightning
	[86516] = {false, true, false, true}, --Fiery Rage
	[62668] = {false, true, false, true}, --Fire Clench
	[62671] = {false, true, false, true}, --Fire Clench
	[62679] = {false, true, false, true}, --Fire Clench
	[42977] = {true, false, false, true}, --Fire Ring
	[38985] = {true, false, false, true}, --Flame Clench
	[40984] = {true, false, false, true}, --Flame Clench
	[41009] = {true, false, false, true}, --Flame Clench
	[42997] = {true, false, false, true}, --Flame Pulsar
	[41048] = {true, false, false, true}, --Flame Reach
	[62691] = {false, true, false, true}, --Flame Reach dot
	[40948] = {true, false, false, true}, --Flame Touch
	[40957] = {true, false, false, true}, --Flame Touch
	[40965] = {true, false, false, true}, --Flame Touch
	[62659] = {false, true, false, true}, --Flame Touch dot
	[62662] = {false, true, false, true}, --Flame Touch dot
	[62665] = {false, true, false, true}, --Flame Touch dot
	[48991] = {true, false, false, true}, --Force Pulse (Fire)
	[48992] = {true, false, false, true}, --Force Pulse (Frost)
	[48994] = {true, false, false, true}, --Force Pulse (Shock)
	[38989] = {true, false, false, true}, --Frost Clench
	[40988] = {true, false, false, true}, --Frost Clench
	[41013] = {true, false, false, true}, --Frost Clench
	[62702] = {false, true, false, true}, --Frost Clench dot
	[62705] = {false, true, false, true}, --Frost Clench dot
	[62711] = {false, true, false, true}, --Frost Clench dot
	[42999] = {true, false, false, true}, --Frost Pulsar
	[41051] = {true, false, false, true}, --Frost Reach
	[62721] = {false, true, false, true}, --Frost Reach dot
	[42979] = {true, false, false, true}, --Frost Ring
	[40950] = {true, false, false, true}, --Frost Touch
	[40959] = {true, false, false, true}, --Frost Touch
	[40967] = {true, false, false, true}, --Frost Touch
	[62695] = {false, true, false, true}, --Frost Touch dot
	[62698] = {false, true, false, true}, --Frost Touch dot
	[62701] = {false, true, false, true}, --Frost Touch dot
	[15385] = {true, false, true, true}, --Heavy Attack (Fire)
	[16321] = {true, false, true, true}, --Heavy Attack (Fire), full
	[18405] = {true, false, true, true}, --Heavy Attack (Frost)
	[18406] = {true, false, true, true}, --Heavy Attack (Frost), full
	[18396] = {false, true, true, true}, --Heavy Attack (Shock)
	[86523] = {false, true, false, true}, --Icy Rage
	[16165] = {true, false, true, true}, --Light Attack (Fire)
	[16277] = {true, false, true, true}, --Light Attack (Frost)
	[18350] = {true, false, true, true}, --Light Attack (Shock)
	[38993] = {true, false, false, true}, --Shock Clench
	[40991] = {true, false, false, true}, --Shock Clench
	[41016] = {true, false, false, true}, --Shock Clench
	[62733] = {false, true, false, true}, --Shock Clench dot
	[62733] = {false, true, false, true}, --Shock Clench dot
	[62742] = {false, true, false, true}, --Shock Clench dot
	[62734] = {false, true, false, true}, --Shock Clench Explosion
	[62734] = {false, true, false, true}, --Shock Clench Explosion
	[62743] = {false, true, false, true}, --Shock Clench Explosion
	[19277] = {true, false, false, true}, --Shock Pulse
	[41054] = {true, false, false, true}, --Shock Reach
	[62768] = {false, true, false, true}, --Shock Reach dot
	[42981] = {true, false, false, true}, --Shock Ring
	[29089] = {true, false, false, true}, --Shock Touch
	[40962] = {true, false, false, true}, --Shock Touch
	[40970] = {true, false, false, true}, --Shock Touch
	[62722] = {false, true, false, true}, --Shock Touch dot
	[62729] = {false, true, false, true}, --Shock Touch dot
	[62731] = {false, true, false, true}, --Shock Touch dot
	[43001] = {true, false, false, true}, --Storm Pulsar
	[86529] = {false, true, false, true}, --Thunderous Rage
	[45505] = {true, false, false, true}, --Tri Focus (Shock)
	[62835] = {false, true, false, true}, --Unstable Wall of Fire
	[62831] = {true, false, false, true}, --Unstable Wall of Fire Explosion
	[62863] = {false, true, false, true}, --Unstable Wall of Frost
	[62857] = {true, false, false, true}, --Unstable Wall of Frost Explosion
	[62890] = {false, true, false, true}, --Unstable Wall of Storms
	[62889] = {true, false, false, true}, --Unstable Wall of Storms Explosion
	[23898] = {true, false, false, true}, --Burning Embers
	[44376] = {false, true, false, true}, --Burning Embers dot
	[32123] = {true, false, false, true}, --Burning Talons
	[32125] = {false, true, false, true}, --Burning Talons (dot)
	[32135] = {true, false, false, true}, --Choking Talons
	[34794] = {false, true, false, true}, --Cinder Storm
	[33853] = {false, true, false, true}, --Corrosive Armor
	[33715] = {true, false, false, true}, --Deep Breath (1st)
	[33717] = {true, false, false, true}, --Deep Breath (2nd)
	[33732] = {true, false, false, true}, --Draw Essence (1st)
	[33734] = {true, false, false, true}, --Draw Essence (2nd)
	[32229] = {true, false, false, true}, --Empowering Chains
	[34048] = {true, false, false, true}, --Engulfing Flames
	[34050] = {false, true, false, true}, --Engulfing Flames dot
	[33820] = {false, true, false, true}, --Eruption
	[33817] = {false, true, false, true}, --Eruption (dot)
	[32716] = {true, false, false, true}, --Ferocious Leap
	[23924] = {true, false, false, true}, --Flame Lash
	[61958] = {true, false, false, true}, --Flames of Oblivion
	[33882] = {true, false, false, true}, --Fragmented Shield
	[33842] = {false, true, false, true}, --Magma Shell
	[23819] = {true, false, false, true}, --Molten Whip
	[34039] = {true, false, false, true}, --Noxious Breath
	[34041] = {false, true, false, true}, --Noxious Breath (dot)
	[32199] = {true, false, false, true}, --Obsidian Shard
	[54937] = {true, false, false, true}, --Petrify
	[23919] = {true, false, false, true}, --Power Lash
	[23919] = {true, false, false, true}, --Power Lash
	[34341] = {true, false, false, true}, --Shattering Rocks
	[33988] = {false, true, false, true}, --Shifting Standard
	[33993] = {false, true, false, true}, --Shifting Standard
	[34022] = {false, true, false, true}, --Standard of Might
	[32205] = {true, false, false, true}, --Stone Giant
	[33669] = {true, false, false, true}, --Take Flight
	[23778] = {true, false, false, true}, --Unrelenting Grip
	[23915] = {true, false, false, true}, --Venomous Claw
	[44372] = {false, true, false, true}, --Venomous Claw
	[23844] = {false, true, false, true}, --Volatile Armor
	[62541] = {false, true, false, true}, --Blade Cloak
	[62569] = {false, true, false, true}, --Blade Cloak
	[40687] = {true, false, false, true}, --Blood Craze
	[40688] = {true, false, false, true}, --Blood Craze
	[40690] = {false, true, false, true}, --Blood Craze Bleed
	[40599] = {false, true, false, true}, --Bloodthirst
	[40628] = {true, false, false, true}, --Flying Blade
	[18622] = {true, false, true, true}, --Heavy Attack (DW main), full
	[17170] = {true, false, true, true}, --Heavy Attack (DW)
	[17169] = {true, false, true, true}, --Heavy Attack (DW), full
	[16499] = {true, false, true, true}, --Light Attack (DW)
	[40590] = {false, true, false, true}, --Rapid Strikes
	[86396] = {false, true, false, true}, --Rend
	[40675] = {true, false, false, true}, --Rending Slashes
	[40676] = {true, false, false, true}, --Rending Slashes
	[40678] = {false, true, false, true}, --Rending Slashes Bleed
	[40619] = {true, false, false, true}, --Shrouded Daggers
	[68840] = {true, false, false, true}, --Shrouded Daggers (2nd)
	[68841] = {true, false, false, true}, --Shrouded Daggers (3rd)
	[40744] = {true, false, false, true}, --Steel Tornado
	[86414] = {false, true, false, true}, --Thrive in Chaos
	[40731] = {true, false, false, true}, --Whirling Blades
	[42598] = {true, false, false, true}, --Dawnbreaker of Smiting
	[62317] = {false, true, false, true}, --Dawnbreaker of Smiting dot
	[42586] = {true, false, false, true}, --Flawless Dawnbreaker
	[62313] = {false, true, false, true}, --Flawless Dawnbreaker dot
	[42775] = {false, true, false, true}, --Lightweight Beast Trap
	[42774] = {false, true, false, true}, --Lightweight Beast Trap dot
	[42751] = {false, true, false, true}, --Rearming Trap
	[42756] = {false, true, false, true}, --Rearming Trap 2
	[42754] = {false, true, false, true}, --Rearming Trap dot
	[42696] = {true, false, false, true}, --Silver Leash
	[42671] = {true, false, false, true}, --Silver Shards
	[46743] = {true, false, false, true}, --Absorb Magicka
	[46746] = {true, false, false, true}, --Absorb Stamina
	[17904] = {true, false, false, true}, --Befouled Weapon
	[17899] = {true, false, false, true}, --Charged Weapon
	[46749] = {true, false, false, true}, --Damage Health
	[93307] = {false, false, false, false}, --Defiler
	[17895] = {true, false, false, true}, --Fiery Weapon
	[17897] = {true, false, false, true}, --Frozen Weapon
	[84502] = {false, true, false, false}, --Grothdarr
	[80561] = {false, true, false, false}, --Iceheart
	[80525] = {false, true, false, false}, --Illambris (fire)
	[80526] = {false, true, false, false}, --Illambris (lightning)
	[83409] = {true, false, false, false}, --Infernal Guardian
	[80565] = {false, true, false, false}, --Kra'gh
	[28919] = {true, false, false, true}, --Life Drain
	[59498] = {false, true, false, false}, --Mephala's Web
	[59593] = {true, false, false, false}, --Nerien'eth
	[17902] = {true, false, false, true}, --Poisoned Weapon
	[40337] = {true, false, false, true}, --Prismatic Weapon
	[80606] = {true, false, false, false}, --Selene
	[80544] = {true, false, false, false}, --Sellistrix
	[80980] = {false, false, false, false}, --Shadowrend (base attack)
	[80989] = {false, false, false, false}, --Shadowrend (tail sweep)
	[80522] = {false, true, false, false}, --Stormfist (lightning)
	[80521] = {true, false, false, false}, --Stormfist (physical)
	[80865] = {true, false, false, false}, --Tremorscale
	[61273] = {true, false, false, false}, --Valkyn Skoria (splash)
	[59596] = {true, false, false, false}, --Valkyn Skoria (target hit)
	[80490] = {true, false, false, false}, --Velidreth
	[102136] = {false, true, false, false}, --Zaan	
	[43036] = {false, true, false, true}, --Degeneration
	[63469] = {true, false, false, true}, --Ice Comet
	[63466] = {false, true, false, true}, --Ice Comet dot
	[42355] = {true, false, false, true}, --Scalding Rune
	[42351] = {false, true, false, true}, --Scalding Rune dot
	[63487] = {true, false, false, true}, --Shooting Star
	[63484] = {false, true, false, true}, --Shooting Star (dot)
	[43041] = {false, true, false, true}, --Structured Entropy
	[42333] = {true, false, false, true}, --Volcanic Rune
	[35901] = {true, false, false, true}, --Ambush
	[62130] = {true, false, false, true}, --Assassins Scourge
	[62138] = {true, false, false, true}, --Assassins Will
	[36244] = {true, false, false, true}, --Concealed Weapon
	[33219] = {false, false, false, false}, --Corrode (pet)
	[51556] = {false, false, false, false}, --Corrode (pet)
	[37907] = {false, true, false, true}, --Crippling Grasp dot
	[37910] = {true, false, false, true}, --Crippling Grasp
	[37916] = {false, true, false, true}, --Crippling Grasp dot
	[37919] = {true, false, false, true}, --Crippling Grasp
	[37890] = {false, true, false, true}, --Debilitate
	[35941] = {true, false, false, true}, --Funnel Health
	[35596] = {true, false, false, true}, --Impale
	[37527] = {true, false, false, true}, --Incapacitating Strike
	[37532] = {true, false, false, true}, --Incapacitating Strike
	[35590] = {true, false, false, true}, --Killers Blade
	[35884] = {true, false, false, true}, --Lotus Fan
	[35885] = {false, true, false, true}, --Lotus Fan dot
	[36145] = {true, false, false, true}, --Malefic Wreath
	[37937] = {true, false, false, true}, --Power Extraction
	[36130] = {false, true, false, true}, --Prolonged Suffering
	[64022] = {false, true, false, true}, --Refreshing Path
	[37950] = {true, false, false, true}, --Sap Essence
	[37545] = {true, false, false, true}, --Soul Harvest
	[36211] = {true, false, false, true}, --Soul Tether
	[36208] = {false, true, false, true}, --Soul Tether dot
	[35949] = {true, false, false, true}, --Swallow Soul
	[37798] = {true, false, false, true}, --Twisting Path
	[37717] = {false, true, false, true}, --Veil of Blades
	[21929] = {false, true, false, true}, --Poisoned
	[16212] = {false, true, true, true}, --Heavy Attack (Resto)
	[16145] = {true, false, true, true}, --Light Attack (Resto)
	[23428] = {false, false, false, false}, --Atronach Zap (pet)
	[62187] = {false, true, false, true}, --Boundless Storm
	[29528] = {false, false, false, false}, --Claw (pet)
	[47560] = {true, false, false, true}, --Crystal Blast
	[47569] = {true, false, false, true}, --Crystal Fragments
	[29983] = {false, true, false, true}, --Daedric Minefield
	[30512] = {true, false, false, true}, --Daedric Prey
	[44514] = {true, false, false, true}, --Daedric Prey (AoE)
	[29948] = {false, true, false, true}, --Daedric Tomb
	[30343] = {true, false, false, true}, --Endless Fury
	[77266] = {false, true, false, true}, --Familiar Damage Pulse
	[27850] = {false, false, false, false}, --Familiar Melee (pet)
	[30578] = {true, false, false, true}, --Greater Storm Atronach
	[30524] = {true, false, false, true}, --Haunting Curse
	[30245] = {false, true, false, true}, --Hurricane
	[45194] = {true, false, false, true}, --Implosion (lightning)
	[82806] = {true, false, false, true}, --Implosion (physical)
	[30303] = {false, true, false, true}, --Lightning Flood
	[30288] = {false, true, false, true}, --Liquid Lightning
	[30331] = {true, false, false, true}, --Mages Wrath
	[30334] = {true, false, false, true}, --Mages' Wrath Explosion
	[24798] = {false, true, false, true}, --Overload Heavy Attack
	[24792] = {true, false, false, true}, --Overload Light Attack
	[24811] = {false, true, false, true}, --Power Overload Heavy Attack
	[30096] = {true, false, false, true}, --Shattering Prison
	[30217] = {true, false, false, true}, --Streak
	[30556] = {true, false, false, true}, --Summon Charged Atronach
	[80438] = {false, true, false, true}, --Suppression Field
	[29529] = {false, false, false, false}, --Tail spike (pet)
	[24617] = {false, false, false, false}, --Zap (pet)
	[43083] = {false, true, false, true}, --Consuming Trap
	[43109] = {false, true, false, true}, --Shatter Soul
	[43099] = {false, true, false, true}, --Soul Assault
	[43067] = {false, true, false, true}, --Soul Splitting Trap
	[26983] = {true, false, false, true}, --Aurora Javelin
	[26992] = {true, false, false, true}, --Binding Javelin
	[27200] = {false, true, false, true}, --Biting Jabs
	[44435] = {false, true, false, true}, --Biting Jabs (new in 3.3.)
	[27168] = {true, false, false, true}, --Blazing Spear
	[27169] = {false, true, false, true}, --Blazing Spear Pulse
	[80170] = {true, false, false, true}, --Burning Light
	[80170] = {true, false, false, true}, --Burning Light
	[23788] = {true, false, false, true}, --Crescent Sweep
	[24147] = {true, false, false, true}, --Dark Flare
	[23794] = {true, false, false, true}, --Empowering Sweep
	[23727] = {true, false, false, true}, --Explosive Charge
	[27123] = {false, true, false, true}, --Luminous Shards
	[95965] = {false, true, false, true}, --Luninous Shards
	[89716] = {true, false, false, true}, --Power of the Light (1st)
	[27594] = {false, false, false, false}, --Power of the Light (2nd)
	[27209] = {false, true, false, true}, --Puncturing Sweep
	[44439] = {false, true, false, true}, --Puncturing Sweep (new in 3.3.)
	[89684] = {true, false, false, true}, --Purifying Light (1st)
	[27565] = {false, false, false, false}, --Purifying Light (2nd)
	[62604] = {false, true, false, true}, --Radial Sweep (dot)
	[62612] = {false, true, false, true}, --Radial Sweep (dot)
	[63960] = {false, true, false, true}, --Radiant Destruction
	[63964] = {false, true, false, true}, --Radiant Destruction
	[27514] = {true, false, false, true}, --Radiant Ward
	[27514] = {true, false, false, true}, --Radiant Ward
	[24195] = {true, false, false, true}, --Reflective Light
	[24197] = {false, true, false, true}, --Reflective Light (dot)
	[80176] = {false, true, false, true}, --Ritual of Retribution
	[24157] = {true, false, false, true}, --Solar Barrage
	[24323] = {false, true, false, true}, --Solar Disturbance
	[24304] = {false, true, false, true}, --Solar Prison
	[23872] = {true, false, false, true}, --Toppling Charge
	[68757] = {true, false, false, true}, --Total Dark
	[27312] = {true, false, false, true}, --Unstable Core
	[24180] = {true, false, false, true}, --Vampires Bane
	[24182] = {false, true, false, true}, --Vampires Bane (dot)
	[86295] = {true, false, false, true}, --Berserker Rage
	[39769] = {true, false, false, true}, --Brawler
	[39770] = {false, true, false, true}, --Brawler Bleed
	[39754] = {true, false, false, true}, --Carve
	[39755] = {false, true, false, true}, --Carve Bleed
	[39824] = {true, false, false, true}, --Critical Rush
	[39964] = {true, false, false, true}, --Dizzying Swing
	[39957] = {true, false, false, true}, --Executioner
	[45445] = {true, false, false, true}, --Forceful
	[17162] = {true, false, true, true}, --Heavy Attack (2H)
	[17163] = {true, false, true, true}, --Heavy Attack (2H), full
	[16037] = {true, false, true, true}, --Light Attack (2H)
	[86284] = {true, false, false, true}, --Onslaught
	[39942] = {true, false, false, true}, --Reverse Slice
	[39945] = {true, false, false, true}, --Reverse Slice (Splash)
	[39811] = {true, false, false, true}, --Stampede
	[40008] = {true, false, false, true}, --Wrecking Blow
	[38956] = {false, true, false, true}, --Accelerating Drain
	[38968] = {false, true, false, true}, --Baleful Mist
	[41923] = {false, true, false, true}, --Bat Swarm
	[41931] = {false, true, false, true}, --Clouding Swarm
	[41941] = {false, true, false, true}, --Devouring Swarm
	[41866] = {false, true, false, true}, --Drain Essence
	[41902] = {false, true, false, true}, --Invigorating Drain
	[94047] = {false, true, false, true}, --Arctic Blast
	[89128] = {true, false, false, true}, --Crushing Swipe (pet)
	[89220] = {true, false, false, true}, --Crushing Swipe (pet)
	[86002] = {true, false, false, true}, --Cutting Dive
	[94424] = {true, false, false, true}, --Deep Fissure
	[86030] = {true, false, false, true}, --Fetcher Infection
	[94090] = {false, true, false, true}, --Gripping Shards
	[86034] = {true, false, false, true}, --Growing Swarm
	[92160] = {true, false, false, true}, --Guardian Savagery
	[91974] = {true, false, false, true}, --Guardian's Wrath (pet)
	[94204] = {false, true, false, true}, --Northern Storm
	[94221] = {true, false, false, true}, --Permafrost
	[93619] = {true, false, false, true}, --Screaming Cliff Racer
	[93794] = {true, false, false, true}, --Subterranean Assault
	[89135] = {true, false, false, true}, --Swipe (pet)
	[89219] = {true, false, false, true}, --Swipe Wild Guardian (pet)
	[88802] = {false, true, false, true}, --Winters Revenge
	[79025] = {true, false, false, true}, --Creeping Ravage Health
	[79707] = {true, false, false, true}, --Ravage Health
	[21925] = {true, false, false, true}, --Diseased
}

if GetAPIVersion() > 100022 then 

	AbilityData = {
	
		[40267] = {false, true, false, true}, --Anti-Calvary Caltrops
		[61493] = {false, false, false, true}, --Inevitable Detonation
		[61502] = {false, false, false, true}, --Proximity Detonation
		[40254] = {false, false, false, true}, --Razor Caltrops
		[40252] = {false, true, false, true}, --Razor Caltrops dot
		[28882] = {true, false, false, true}, --Snipe
		[28877] = {false, true, false, true}, --Volley
		[28879] = {true, false, false, true}, --Scatter Shot
		[38722] = {true, false, false, true}, --Arrow Spray
		[28869] = {true, false, false, true}, --Poison Arrow
		[44540] = {false, true, false, true}, --Poison Arrow (Dot)
		[86563] = {false, true, false, true}, --Rapid Fire
		[21929] = {false, true, false, true}, --Poisoned
		[38685] = {true, false, false, true}, --Lethal Arrow
		[38690] = {false, true, false, true}, --Endless Hail
		[38672] = {true, false, false, true}, --Magnum Shot
		[38723] = {true, false, false, true}, --Bombard
		[38645] = {true, false, false, true}, --Venom Arrow
		[44545] = {false, true, false, true}, --Venom Arrow (Dot)
		[85260] = {false, true, false, true}, --Toxic Barrage
		[85261] = {false, true, false, true}, --Toxic Barrage (Dot)
		[38687] = {true, false, false, true}, --Focused Aim
		[38696] = {false, true, false, true}, --Arrow Barrage
		[38669] = {true, false, false, true}, --Draining Shot
		[38724] = {true, false, false, true}, --Acid Spray
		[38703] = {false, true, false, true}, --Acid Spray (Dot)
		[38660] = {true, false, false, true}, --Poison Injection
		[44549] = {false, true, false, true}, --Poison Injection (Dot)
		[85462] = {true, false, false, true}, --Ballista
		[62912] = {false, true, false, true}, --Blockade of Fire
		[62951] = {false, true, false, true}, --Blockade of Frost
		[62990] = {false, true, false, true}, --Blockade of Storms
		[18084] = {false, true, false, true}, --Burning
		[21481] = {false, true, false, true}, --Chill
		[21487] = {false, true, false, true}, --Concussion
		[46348] = {true, false, false, true}, --Crushing Shock (Fire)
		[46350] = {true, false, false, true}, --Crushing Shock (Frost)
		[46351] = {true, false, false, true}, --Crushing Shock (Shock)
		[83683] = {false, true, false, true}, --Eye of Flame
		[83685] = {false, true, false, true}, --Eye of Frost
		[83687] = {false, true, false, true}, --Eye of Lightning
		[85127] = {false, true, false, true}, --Fiery Rage
		[62668] = {false, true, false, true}, --Fire Clench
		[39149] = {true, false, false, true}, --Fire Ring
		[38985] = {true, false, false, true}, --Flame Clench
		[39162] = {true, false, false, true}, --Flame Pulsar
		[38944] = {true, false, false, true}, --Flame Reach
		[62682] = {false, true, false, true}, --Flame Reach dot
		[29073] = {true, false, false, true}, --Flame Touch
		[62648] = {false, true, false, true}, --Flame Touch dot
		[46356] = {true, false, false, true}, --Force Pulse (Fire)
		[46357] = {true, false, false, true}, --Force Pulse (Frost)
		[46358] = {true, false, false, true}, --Force Pulse (Shock)
		[38989] = {true, false, false, true}, --Frost Clench
		[62702] = {false, true, false, true}, --Frost Clench dot
		[39163] = {true, false, false, true}, --Frost Pulsar
		[38970] = {true, false, false, true}, --Frost Reach
		[62712] = {false, true, false, true}, --Frost Reach dot
		[39151] = {true, false, false, true}, --Frost Ring
		[29078] = {true, false, false, true}, --Frost Touch
		[62692] = {false, true, false, true}, --Frost Touch dot
		[15385] = {true, false, true, true}, --Heavy Attack (Fire)
		[16321] = {true, false, true, true}, --Heavy Attack (Fire), full
		[18405] = {true, false, true, true}, --Heavy Attack (Frost)
		[18406] = {true, false, true, true}, --Heavy Attack (Frost), full
		[18396] = {false, true, true, true}, --Heavy Attack (Shock)
		[85129] = {false, true, false, true}, --Icy Rage
		[16165] = {true, false, true, true}, --Light Attack (Fire)
		[16277] = {true, false, true, true}, --Light Attack (Frost)
		[18350] = {true, false, true, true}, --Light Attack (Shock)
		[38993] = {true, false, false, true}, --Shock Clench
		[62733] = {false, true, false, true}, --Shock Clench dot
		[62743] = {false, true, false, true}, --Shock Clench Explosion
		[19277] = {true, false, false, true}, --Shock Pulse
		[38978] = {true, false, false, true}, --Shock Reach
		[62745] = {false, true, false, true}, --Shock Reach dot
		[39153] = {true, false, false, true}, --Shock Ring
		[29089] = {true, false, false, true}, --Shock Touch
		[62722] = {false, true, false, true}, --Shock Touch dot
		[39167] = {true, false, false, true}, --Storm Pulsar
		[85131] = {false, true, false, true}, --Thunderous Rage
		[45505] = {false, true, true, true}, --Tri Focus (Shock)
		[39054] = {false, true, false, true}, --Unstable Wall of Fire
		[39056] = {true, false, false, true}, --Unstable Wall of Fire Explosion
		[39071] = {false, true, false, true}, --Unstable Wall of Frost
		[39072] = {true, false, false, true}, --Unstable Wall of Frost Explosion
		[39079] = {false, true, false, true}, --Unstable Wall of Storms
		[39080] = {true, false, false, true}, --Unstable Wall of Storms Explosion
		[20660] = {true, false, false, true}, --Burning Embers
		[44373] = {false, true, false, true}, --Burning Embers dot
		[20252] = {true, false, false, true}, --Burning Talons
		[31898] = {false, true, false, true}, --Burning Talons (dot)
		[20251] = {true, false, false, true}, --Choking Talons
		[17879] = {false, true, false, true}, --Corrosive Armor
		[32792] = {true, false, false, true}, --Deep Breath (1st)
		[32794] = {true, false, false, true}, --Deep Breath (2nd)
		[32785] = {true, false, false, true}, --Draw Essence (1st)
		[32787] = {true, false, false, true}, --Draw Essence (2nd)
		[20499] = {true, false, false, true}, --Empowering Chains
		[20930] = {true, false, false, true}, --Engulfing Flames
		[31104] = {false, true, false, true}, --Engulfing Flames dot
		[32714] = {false, true, false, true}, --Eruption
		[32711] = {false, true, false, true}, --Eruption (dot)
		[32716] = {true, false, false, true}, --Ferocious Leap
		[20816] = {true, false, false, true}, --Flame Lash
		[61945] = {true, false, false, true}, --Flames of Oblivion
		[28969] = {true, false, false, true}, --Inferno
		[23806] = {true, false, false, true}, --Lava Whip
		[17875] = {false, true, false, true}, --Magma Shell
		[20805] = {true, false, false, true}, --Molten Whip
		[20944] = {true, false, false, true}, --Noxious Breath
		[31103] = {false, true, false, true}, --Noxious Breath (dot)
		[31820] = {true, false, false, true}, --Obsidian Shard
		[54918] = {true, false, false, true}, --Petrify
		[20824] = {true, false, false, true}, --Power Lash
		[32684] = {true, false, false, true}, --Shattering Rocks
		[54931] = {true, false, false, true}, --Fossilize
		[32960] = {false, true, false, true}, --Shifting Standard
		[32964] = {false, true, false, true}, --Shifting Standard
		[32948] = {false, true, false, true}, --Standard of Might
		[31816] = {true, false, false, true}, --Stone Giant
		[32720] = {true, false, false, true}, --Take Flight
		[20496] = {true, false, false, true}, --Unrelenting Grip
		[20668] = {true, false, false, true}, --Venomous Claw
		[44369] = {false, true, false, true}, --Venomous Claw (dot)
		[20326] = {false, true, false, true}, --Volatile Armor
		[62522] = {false, true, false, true}, --Blade Cloak
		[38845] = {true, false, false, true}, --Blood Craze
		[38847] = {true, false, false, true}, --Blood Craze (Off Hand)
		[38848] = {false, true, false, true}, --Blood Craze Bleed
		[38846] = {false, true, false, true}, --Bloodthirst
		[62547] = {false, true, false, true}, --Deadly Cloak (Blade Cloak)
		[28607] = {false, true, false, true}, --Flurry
		[38910] = {true, false, false, true}, --Flying Blade
		[21157] = {true, false, false, true}, --Hidden Blade
		[85156] = {false, true, false, true}, --Lacerate
		[62529] = {false, true, false, true}, --Quick Cloak (Blade Cloak)
		[38857] = {false, true, false, true}, --Rapid Strikes
		[85192] = {false, true, false, true}, --Rend
		[38839] = {true, false, false, true}, --Rending Slashes
		[38840] = {true, false, false, true}, --Rending Slashes (Off Hand)
		[38841] = {false, true, false, true}, --Rending Slashes Bleed
		[38914] = {true, false, false, true}, --Shrouded Daggers
		[38861] = {true, false, false, true}, --Steel Tornado
		[85182] = {false, true, false, true}, --Thrive in Chaos
		[28379] = {true, false, false, true}, --Twin Slashes
		[35312] = {true, false, false, true}, --Twin Slashes (Off hand)
		[29293] = {false, true, false, true}, --Twin Slashes Bleed
		[38891] = {true, false, false, true}, --Whirling Blades
		[28591] = {true, false, false, true}, --Whirlwind
		[40158] = {true, false, false, true}, --Dawnbreaker of Smiting
		[62314] = {false, true, false, true}, --Dawnbreaker of Smiting dot
		[40161] = {true, false, false, true}, --Flawless Dawnbreaker
		[62310] = {false, true, false, true}, --Flawless Dawnbreaker dot
		[40376] = {false, true, false, true}, --Lightweight Beast Trap
		[40375] = {false, true, false, true}, --Lightweight Beast Trap dot
		[40389] = {false, true, false, true}, --Rearming Trap
		[40392] = {false, true, false, true}, --Rearming Trap 2
		[40385] = {false, true, false, true}, --Rearming Trap dot
		[40336] = {true, false, false, true}, --Silver Leash
		[40300] = {true, false, false, true}, --Silver Shards
		[46743] = {true, false, false, true}, --Absorb Magicka
		[46746] = {true, false, false, true}, --Absorb Stamina
		[17904] = {true, false, false, true}, --Befouled Weapon
		[17899] = {true, false, false, true}, --Charged Weapon
		[46749] = {true, false, false, true}, --Damage Health
		[93307] = {false, false, false, false}, --Defiler
		[97883] = {false, true, false, false}, --Domihaus (fire)
		[17895] = {true, false, false, true}, --Fiery Weapon
		[17897] = {true, false, false, true}, --Frozen Weapon
		[84502] = {false, true, false, false}, --Grothdarr
		[80561] = {false, true, false, false}, --Iceheart
		[80525] = {false, true, false, false}, --Illambris (fire)
		[80526] = {false, true, false, false}, --Illambris (lightning)
		[83409] = {true, false, false, false}, --Infernal Guardian
		[80565] = {false, true, false, false}, --Kra'gh
		[28919] = {true, false, false, true}, --Life Drain
		[107094] = {false, true, false, false}, --Mantle of Siroria
		[59498] = {false, true, false, false}, --Mephala's Web
		[59593] = {true, false, false, false}, --Nerien'eth
		[17902] = {true, false, false, true}, --Poisoned Weapon
		[40337] = {true, false, false, true}, --Prismatic Weapon
		[80606] = {true, false, false, false}, --Selene
		[80544] = {true, false, false, false}, --Sellistrix
		[80980] = {false, false, false, false}, --Shadowrend (base attack)
		[80989] = {false, false, false, false}, --Shadowrend (tail sweep)
		[80522] = {false, true, false, false}, --Stormfist (lightning)
		[80521] = {true, false, false, false}, --Stormfist (physical)
		[80865] = {true, false, false, false}, --Tremorscale
		[61273] = {true, false, false, false}, --Valkyn Skoria (splash)
		[59596] = {true, false, false, false}, --Valkyn Skoria (target hit)
		[80490] = {true, false, false, false}, --Velidreth
		[102136] = {false, true, false, false}, --Zaan
		[40457] = {false, true, false, true}, --Degeneration
		[63457] = {true, false, false, true}, --Ice Comet
		[63454] = {false, true, false, true}, --Ice Comet dot
		[40469] = {true, false, false, true}, --Scalding Rune
		[40468] = {false, true, false, true}, --Scalding Rune dot
		[63474] = {true, false, false, true}, --Shooting Star
		[63471] = {false, true, false, true}, --Shooting Star (dot)
		[40452] = {false, true, false, true}, --Structured Entropy
		[40473] = {true, false, false, true}, --Volcanic Rune
		[25485] = {true, false, false, true}, --Ambush
		[61932] = {true, false, false, true}, --Assassin's Scourge
		[61907] = {true, false, false, true}, --Assassin's Will
		[61930] = {true, false, false, true}, --Assassin's Will
		[25267] = {true, false, false, true}, --Concealed Weapon
		[33219] = {false, false, false, true}, --Corrode (pet)
		[51556] = {false, false, false, true}, --Corrode (pet)
		[36963] = {true, false, false, true}, --Crippling Grasp
		[36960] = {false, true, false, true}, --Crippling Grasp dot
		[36947] = {false, true, false, true}, --Debilitate
		[34838] = {true, false, false, true}, --Funnel Health
		[34851] = {true, false, false, true}, --Impale
		[36508] = {true, false, false, true}, --Incapacitating Strike
		[34843] = {true, false, false, true}, --Killers Blade
		[25494] = {true, false, false, true}, --Lotus Fan
		[35336] = {false, true, false, true}, --Lotus Fan dot
		[36901] = {true, false, false, true}, --Power Extraction
		[64001] = {false, true, false, true}, --Path of Darkness (Refreshing Path)
		[36891] = {true, false, false, true}, --Sap Essence
		[36514] = {true, false, false, true}, --Soul Harvest
		[35465] = {true, false, false, true}, --Soul Tether
		[35462] = {false, true, false, true}, --Soul Tether dot
		[25260] = {true, false, false, true}, --Surprise Attack
		[34835] = {true, false, false, true}, --Swallow Soul
		[36052] = {false, true, false, true}, --Twisting Path
		[36490] = {false, true, false, true}, --Veil of Blades
		[108936] = {false, false, false, true}, --Whirlwind (pet)
		[21925] = {false, true, false, true}, --Diseased
		[21929] = {false, true, false, true}, --Poisoned
		[79025] = {false, true, false, true}, --Creeping Ravage Health
		[79707] = {false, true, false, true}, --Ravage Health
		[81275] = {true, false, false, true}, --Creeping Ravage Health (Crown Store)
		[81274] = {true, false, false, true}, --Ravage Health (Crown Store)
		[16212] = {false, true, true, true}, --Heavy Attack (Resto)
		[16145] = {true, false, true, true}, --Light Attack (Resto)
		[46743] = {true, false, false, true}, --Absorb Magicka
		[23428] = {false, true, false, true}, --Atronach Zap (Storm Atronach)
		[23214] = {false, true, false, true}, --Boundless Storm
		[29528] = {false, false, false, false}, --Claw (Unstable Clannfear)
		[46331] = {true, false, false, true}, --Crystal Blast
		[46324] = {true, false, false, true}, --Crystal Fragments
		[43714] = {true, false, false, true}, --Crystal Shard
		[24327] = {true, false, false, true}, --Daedric Curse
		[25161] = {false, true, false, true}, --Daedric Minefield
		[24829] = {false, true, false, true}, --Daedric Mines
		[24329] = {true, false, false, true}, --Daedric Prey
		[24843] = {false, true, false, true}, --Daedric Tomb
		[19109] = {true, false, false, true}, --Endless Fury
		[108844] = {false, true, false, true}, --Familiar Damage Pulse (Unstable Familirar)
		[77186] = {false, true, false, true}, --Familiar Damage Pulse (Volatile Familiar)
		[27850] = {false, false, false, false}, --Familiar Melee (Unstable Familirar)
		[23664] = {true, false, false, true}, --Greater Storm Attronach
		[24331] = {true, false, false, true}, --Haunting Curse
		[23232] = {false, true, false, true}, --Hurricane
		[45194] = {true, false, false, true}, --Implosion (Lightning)
		[82806] = {true, false, false, true}, --Implosion (Physical)
		[28027] = {false, false, false, false}, --Kick (Winged Twilight/Twilight Tormentor)
		[23208] = {false, true, false, true}, --Lightning Flood
		[23211] = {false, true, false, true}, --Lightning Form
		[29809] = {true, false, false, true}, --Lightning Strike (Charged Atronach)
		[23202] = {false, true, false, true}, --Liquid Lightning
		[23189] = {false, true, false, true}, --Lightning Splash
		[18718] = {true, false, false, true}, --Mages' Fury
		[19123] = {true, false, false, true}, --Magess' Wraith
		[24798] = {false, true, false, true}, --Overload Heavy Attack
		[24792] = {true, false, false, true}, --Overload Light Attack
		[100118] = {true, false, false, true}, --Petrify (Rune Cage)
		[24811] = {false, true, false, true}, --Power Overload Heavy
		[28309] = {true, false, false, true}, --Shattering Prison
		[23239] = {true, false, false, true}, --Streak
		[23667] = {true, false, false, true}, --Summon Charged Atronach
		[23659] = {true, false, false, true}, --Summon Storm Atronach
		[80435] = {false, true, false, true}, --Suppression Field
		[29528] = {false, false, false, false}, --Tail Spike (Unstable Clannfear)
		[24617] = {false, false, false, false}, --Zap (Winged Twilight/Twilight Tormentor)
		[40317] = {false, true, false, true}, --Consuming Trap
		[40414] = {false, true, false, true}, --Shatter Soul
		[40420] = {false, true, false, true}, --Soul Assault
		[40328] = {false, true, false, true}, --Soul Splitting Trap
		[26800] = {true, false, false, true}, --Aurora Javelin
		[26804] = {true, false, false, true}, --Binding Javelin
		[44432] = {false, true, false, true}, --Biting Jabs
		[26794] = {false, true, false, true}, --Biting Jabs (splash)
		[26871] = {true, false, false, true}, --Blazing Spear
		[26879] = {false, true, false, true}, --Blazing Spear Pulse
		[80170] = {true, false, false, true}, --Burning Light
		[80170] = {true, false, false, true}, --Burning Light
		[22139] = {true, false, false, true}, --Crescent Sweep
		[22110] = {true, false, false, true}, --Dark Flare
		[22144] = {true, false, false, true}, --Empowering Sweep
		[22165] = {true, false, false, true}, --Explosive Charge
		[26859] = {true, false, false, true}, --Luminous Shards
		[95955] = {false, true, false, true}, --Luminous Shards (dot)
		[89828] = {true, false, false, true}, --Power of the Light (1st)
		[27567] = {false, false, false, false}, --Power of the Light (2nd)
		[44436] = {false, true, false, true}, --Puncturing Sweep
		[26799] = {false, true, false, true}, --Puncturing Sweep (splash)
		[89825] = {true, false, false, true}, --Purifying Light (1st)
		[27544] = {false, false, false, false}, --Purifying Light (2nd)
		[22138] = {false, true, false, true}, --Radial Sweep
		[62550] = {false, true, false, true}, --Radial Sweep (dot)
		[62606] = {false, true, false, true}, --Radial Sweep (dot)
		[62598] = {false, true, false, true}, --Radial Sweep (dot)
		[63961] = {false, true, false, true}, --Radiant Oppression
		[22182] = {true, false, false, true}, --Radiant Ward
		[21732] = {true, false, false, true}, --Reflective Light
		[21734] = {false, true, false, true}, --Reflective Light (dot)
		[80172] = {false, true, false, true}, --Ritual of Retribution
		[100218] = {true, false, false, true}, --Solar Barrage
		[21759] = {false, true, false, true}, --Solar Disturbance
		[21756] = {false, true, false, true}, --Solar Prison
		[21726] = {true, false, false, true}, --Sun Fire
		[21728] = {false, true, false, true}, --Sun Fire (DoT)
		[22178] = {true, false, false, true}, --Sun Shield
		[15544] = {true, false, false, true}, --Toppling Charge
		[68729] = {true, false, false, true}, --Total Dark
		[22005] = {true, false, false, true}, --Unstable Core
		[21729] = {true, false, false, true}, --Vampires Bane
		[21731] = {false, true, false, true}, --Vampires Bane (dot)
		[28279] = {true, false, false, true}, --Uppercut
		[28449] = {true, false, false, true}, --Critical Charge
		[20919] = {true, false, false, true}, --Cleave
		[31059] = {false, true, false, true}, --Cleave Bleed
		[28302] = {true, false, false, true}, --Reverse Slash
		[83216] = {true, false, false, true}, --Berserker Strike
		[45431] = {false, true, false, true}, --Heavy Weapons Bleed
		[38814] = {true, false, false, true}, --Dizzying Swing
		[38792] = {true, false, false, true}, --Stampede
		[38745] = {true, false, false, true}, --Carve
		[38747] = {false, true, false, true}, --Carve Bleed
		[38823] = {true, false, false, true}, --Reverse Slice
		[38827] = {true, false, false, true}, --Reverse Slice (2nd)
		[83229] = {true, false, false, true}, --Onslaught
		[38807] = {true, false, false, true}, --Wrecking Blow
		[38782] = {true, false, false, true}, --Critical Rush
		[38754] = {true, false, false, true}, --Brawler
		[38759] = {false, true, false, true}, --Brawler Bleed
		[38819] = {true, false, false, true}, --Executioner
		[83238] = {true, false, false, true}, --Berserker Rage
		[42060] = {true, false, false, true}, --Inner Beast
		[42056] = {true, false, false, true}, --Inner Rage
		[80107] = {true, false, false, true}, --Shadow Silk (not synergy)
		[80129] = {true, false, false, true}, --Tangling Webs (not synergy)
		[38956] = {false, true, false, true}, --Accelerating Drain
		[38968] = {false, true, false, true}, --Baleful Mist
		[32625] = {false, true, false, true}, --Bat Swarm
		[38935] = {false, true, false, true}, --Clouding Swarm
		[38934] = {false, true, false, true}, --Devouring Swarm
		[32893] = {false, true, false, true}, --Drain Essence
		[38949] = {false, true, false, true}, --Invigorating Drain
		[87256] = {false, true, false, true}, --Arctic Blast
		[105907] = {true, false, false, true}, --Crushing Swipe (pet)
		[89128] = {true, false, false, true}, --Crushing Swipe (pet)
		[89220] = {true, false, false, true}, --Crushing Swipe (pet)
		[85999] = {true, false, false, true}, --Cutting Dive
		[94424] = {true, false, false, true}, --Deep Fissure
		[85995] = {true, false, false, true}, --Dive
		[101904] = {true, false, false, true}, --Fetcher Infection
		[88791] = {false, true, false, true}, --Gripping Shards
		[101944] = {true, false, false, true}, --Growing Swarm
		[92160] = {true, false, false, true}, --Guardian Savagery
		[105921] = {true, false, false, true}, --Guardian's Wrath (pet)
	}
end

function GetConstellationData()

	return AbilityData

end